/**
 * @file    web_assets.h
 * @brief   Kontrx — Embedded SPA Web Assets (minified HTML/CSS/JS)
 *
 * Contains:
 *   KONTRX_HTML  — Full Single-Page Application stored as C string literal
 *
 * Pages/sections:
 *   #dashboard   — Live sensor values, relay states, uptime, QR code
 *   #relays      — Per-relay pin mapping and NO/NC state logic
 *   #mqtt        — MQTT broker provisioning
 *   #ota         — OTA firmware upload with OTP validation
 *
 * The SPA uses a tab-based layout (no page reload).
 * fetch('/api/status') polls every 1000 ms for live data.
 */

#ifndef WEB_ASSETS_H
#define WEB_ASSETS_H

#include <stddef.h>

/* ------------------------------------------------------------------ */
/*  The SPA is stored as a single const string literal.               */
/*  The HTTP server task prepends the HTTP/1.1 200 OK headers.        */
/* ------------------------------------------------------------------ */

static const char KONTRX_HTML[] =
"<!DOCTYPE html>"
"<html lang='en'>"
"<head>"
"<meta charset='UTF-8'>"
"<meta name='viewport' content='width=device-width,initial-scale=1'>"
"<title>Kontrx Edge Gateway</title>"
"<link href='https://fonts.googleapis.com/css2?family=Inter:wght@300;400;600;700;900&display=swap' rel='stylesheet'>"
"<style>"
":root{"
  "--bg:#050a14;--card:#0c1628;--card2:#111d35;--border:#1e3a5f;"
  "--accent:#00d4ff;--accent2:#7c3aed;--green:#10b981;--red:#ef4444;"
  "--yellow:#f59e0b;--text:#e2e8f0;--muted:#64748b;--font:'Inter',sans-serif;"
"}"
"*{box-sizing:border-box;margin:0;padding:0}"
"body{background:var(--bg);color:var(--text);font-family:var(--font);min-height:100vh;overflow-x:hidden}"
"body::before{"
  "content:'';position:fixed;top:-50%;left:-50%;width:200%;height:200%;"
  "background:radial-gradient(ellipse at 20% 20%,rgba(0,212,255,.06) 0%,transparent 50%),"
             "radial-gradient(ellipse at 80% 80%,rgba(124,58,237,.06) 0%,transparent 50%);"
  "pointer-events:none;z-index:0"
"}"
"#app{position:relative;z-index:1;max-width:1280px;margin:0 auto;padding:20px}"

/* --- Header --- */
".hdr{display:flex;align-items:center;justify-content:space-between;padding:18px 28px;"
  "background:linear-gradient(135deg,rgba(12,22,40,.9),rgba(17,29,53,.9));"
  "border:1px solid var(--border);border-radius:16px;margin-bottom:24px;"
  "backdrop-filter:blur(20px);box-shadow:0 0 40px rgba(0,212,255,.08)}"
".hdr-logo{display:flex;align-items:center;gap:14px}"
".hdr-logo svg{filter:drop-shadow(0 0 8px rgba(0,212,255,.6))}"
".hdr-title{font-size:1.5rem;font-weight:900;letter-spacing:-.02em;"
  "background:linear-gradient(135deg,#00d4ff,#7c3aed);-webkit-background-clip:text;-webkit-text-fill-color:transparent}"
".hdr-sub{font-size:.7rem;color:var(--muted);letter-spacing:.08em;text-transform:uppercase;margin-top:2px}"
".hdr-status{display:flex;align-items:center;gap:8px;font-size:.8rem;color:var(--muted)}"
".dot{width:8px;height:8px;border-radius:50%;background:var(--green);box-shadow:0 0 8px var(--green);animation:pulse 2s infinite}"
"@keyframes pulse{0%,100%{opacity:1}50%{opacity:.4}}"
".uptime{font-variant-numeric:tabular-nums;color:var(--accent)}"

/* --- Tabs --- */
".tabs{display:flex;gap:6px;margin-bottom:20px;background:rgba(12,22,40,.6);"
  "border:1px solid var(--border);border-radius:12px;padding:6px}"
".tab{flex:1;padding:10px 16px;border:none;cursor:pointer;border-radius:8px;"
  "font-family:var(--font);font-size:.8rem;font-weight:600;letter-spacing:.04em;"
  "text-transform:uppercase;color:var(--muted);background:transparent;transition:all .2s}"
".tab:hover{color:var(--text);background:rgba(30,58,95,.4)}"
".tab.active{color:var(--accent);background:rgba(0,212,255,.1);box-shadow:0 0 20px rgba(0,212,255,.15);border:1px solid rgba(0,212,255,.2)}"
".page{display:none}.page.active{display:block}"

/* --- Cards --- */
".grid{display:grid;gap:16px}"
".grid2{grid-template-columns:repeat(auto-fit,minmax(260px,1fr))}"
".grid3{grid-template-columns:repeat(auto-fit,minmax(200px,1fr))}"
".card{background:linear-gradient(135deg,var(--card),var(--card2));"
  "border:1px solid var(--border);border-radius:14px;padding:20px;"
  "position:relative;overflow:hidden;transition:transform .2s,box-shadow .2s}"
".card:hover{transform:translateY(-2px);box-shadow:0 8px 32px rgba(0,212,255,.1)}"
".card::before{content:'';position:absolute;top:0;left:0;right:0;height:2px;"
  "background:linear-gradient(90deg,var(--accent),var(--accent2));opacity:.4}"
".card-title{font-size:.65rem;text-transform:uppercase;letter-spacing:.12em;color:var(--muted);margin-bottom:10px}"
".card-val{font-size:2rem;font-weight:900;font-variant-numeric:tabular-nums;"
  "background:linear-gradient(135deg,var(--accent),#fff);-webkit-background-clip:text;-webkit-text-fill-color:transparent}"
".card-unit{font-size:.8rem;color:var(--muted);margin-left:4px;font-weight:400;-webkit-text-fill-color:var(--muted)}"
".card-sub{font-size:.75rem;color:var(--muted);margin-top:6px}"

/* --- Relay Grid --- */
".relay-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(120px,1fr));gap:12px}"
".multi-us-grid{display:grid;grid-template-columns:1fr 1fr;gap:4px 16px;font-size:.85rem;margin:6px 0}"
".relay-btn{background:var(--card2);border:1px solid var(--border);border-radius:10px;"
  "padding:14px;cursor:pointer;text-align:center;transition:all .2s;position:relative}"
".relay-btn.on{border-color:var(--green);background:rgba(16,185,129,.12);"
  "box-shadow:0 0 20px rgba(16,185,129,.2)}"
".relay-btn.on .relay-led{background:var(--green);box-shadow:0 0 10px var(--green)}"
".relay-btn.off .relay-led{background:var(--red);box-shadow:0 0 10px var(--red)}"
".relay-led{width:10px;height:10px;border-radius:50%;margin:0 auto 8px;transition:all .3s}"
".relay-name{font-size:.7rem;font-weight:700;letter-spacing:.05em;color:var(--text)}"
".relay-pin{font-size:.6rem;color:var(--muted);margin-top:2px}"
".relay-nc{font-size:.55rem;color:var(--yellow);margin-top:2px;font-weight:600}"

/* --- Config Forms --- */
".form-section{background:var(--card);border:1px solid var(--border);border-radius:14px;padding:24px;margin-bottom:16px}"
".form-section h3{font-size:.85rem;font-weight:700;color:var(--accent);text-transform:uppercase;letter-spacing:.08em;margin-bottom:16px}"
".form-row{display:grid;grid-template-columns:repeat(auto-fit,minmax(200px,1fr));gap:12px;margin-bottom:12px}"
"label{font-size:.72rem;color:var(--muted);display:block;margin-bottom:5px;letter-spacing:.04em;text-transform:uppercase}"
"input,select{width:100%;background:rgba(5,10,20,.6);border:1px solid var(--border);"
  "border-radius:8px;padding:10px 14px;color:var(--text);font-family:var(--font);font-size:.85rem;outline:none;transition:border-color .2s}"
"input:focus,select:focus{border-color:var(--accent);box-shadow:0 0 0 3px rgba(0,212,255,.1)}"
"select option{background:var(--card)}"

/* --- Buttons --- */
".btn{display:inline-flex;align-items:center;gap:8px;padding:10px 20px;border:none;"
  "border-radius:8px;font-family:var(--font);font-size:.82rem;font-weight:600;cursor:pointer;transition:all .2s}"
".btn-primary{background:linear-gradient(135deg,var(--accent),#0099cc);color:#000}"
".btn-primary:hover{transform:translateY(-1px);box-shadow:0 6px 20px rgba(0,212,255,.3)}"
".btn-danger{background:linear-gradient(135deg,var(--red),#c53030);color:#fff}"
".btn-danger:hover{box-shadow:0 6px 20px rgba(239,68,68,.3)}"
".btn-success{background:linear-gradient(135deg,var(--green),#059669);color:#fff}"
".btn-success:hover{box-shadow:0 6px 20px rgba(16,185,129,.3)}"
".btn-sm{padding:6px 14px;font-size:.75rem}"
".btn:disabled{opacity:.4;cursor:not-allowed;transform:none!important}"

/* --- Progress Bar --- */
".progress-wrap{background:rgba(5,10,20,.6);border-radius:999px;height:6px;overflow:hidden;margin:10px 0}"
".progress-bar{height:100%;border-radius:999px;background:linear-gradient(90deg,var(--accent),var(--accent2));"
  "transition:width .3s;width:0%}"

/* --- QR --- */
"#qr-container{display:flex;justify-content:center;padding:20px}"
"#qr-canvas{border-radius:12px;box-shadow:0 0 40px rgba(0,212,255,.2)}"

/* --- Alerts --- */
".alert{padding:12px 16px;border-radius:8px;font-size:.82rem;margin-top:10px}"
".alert-ok{background:rgba(16,185,129,.15);border:1px solid rgba(16,185,129,.4);color:var(--green)}"
".alert-err{background:rgba(239,68,68,.15);border:1px solid rgba(239,68,68,.4);color:var(--red)}"
".alert-warn{background:rgba(245,158,11,.15);border:1px solid rgba(245,158,11,.4);color:var(--yellow)}"
".hidden{display:none!important}"

/* --- OTP field --- */
".otp-wrap{display:flex;gap:8px;align-items:flex-end}"
".otp-wrap input{max-width:240px}"
"</style>"
"</head>"
"<body>"
"<div id='app'>"

/* ============ HEADER ============ */
"<div class='hdr'>"
  "<div class='hdr-logo'>"
    "<svg width='36' height='36' viewBox='0 0 36 36' fill='none'>"
      "<rect width='36' height='36' rx='8' fill='url(#g1)'/>"
      "<path d='M10 18h16M18 10v16' stroke='#000' stroke-width='2.5' stroke-linecap='round'/>"
      "<defs><linearGradient id='g1' x1='0' y1='0' x2='36' y2='36'>"
        "<stop stop-color='#00d4ff'/><stop offset='1' stop-color='#7c3aed'/>"
      "</linearGradient></defs>"
    "</svg>"
    "<div>"
      "<div class='hdr-title'>Kontrx</div>"
      "<div class='hdr-sub'>STM32F407 &nbsp;|&nbsp; Edge Gateway &nbsp;|&nbsp; FW v2.0.0</div>"
    "</div>"
  "</div>"
  "<div class='hdr-status'>"
    "<div class='dot' id='conn-dot'></div>"
    "<span id='conn-lbl'>Online</span>"
    "&nbsp;&nbsp;⏱&nbsp;<span class='uptime' id='uptime-val'>--:--:--</span>"
  "</div>"
"</div>"

/* ============ TABS ============ */
"<div class='tabs'>"
  "<button class='tab active' onclick='showTab(\"dashboard\")'>📊 Dashboard</button>"
  "<button class='tab' onclick='showTab(\"configs\")'>⚙️ Configs</button>"
  "<button class='tab' onclick='showTab(\"mqtt\")'>☁️ MQTT</button>"
  "<button class='tab' onclick='showTab(\"ota\")'>🔄 OTA Update</button>"
"</div>"

/* ============ PAGE: DASHBOARD ============ */
"<div class='page active' id='page-dashboard'>"
  "<div class='grid grid2' style='margin-bottom:16px'>"

    /* Sensor value cards — populated by JS from /api/status */
    "<div id='sensor-cards' style='display:contents'>"
      "<!-- populated by JS -->"
    "</div>"

    /* QR */
    "<div class='card' style='grid-column:span 1'>"
      "<div class='card-title'>📱 Board Identity QR</div>"
      "<div id='qr-container'><canvas id='qr-canvas' width='140' height='140'></canvas></div>"
      "<div id='qr-label' style='text-align:center;font-size:.68rem;color:var(--muted);margin-top:6px'></div>"
    "</div>"
  "</div>"

  /* Relay Status Row */
  "<div class='form-section'>"
    "<h3>⚡ Relay Status</h3>"
    "<div class='relay-grid' id='relay-status-grid'>"
      "<!-- populated by JS -->"
    "</div>"
  "</div>"
"</div>"

/* ============ PAGE: CONFIGS ============ */
"<div class='page' id='page-configs'>"
  "<div class='form-section'>"
    "<h3>⚡ Relay Configuration</h3>"
    "<div id='relay-config-grid'>"
      "<!-- populated by JS -->"
    "</div>"
    "<div style='margin-top:16px;display:flex;gap:10px;flex-wrap:wrap'>"
      "<button class='btn btn-success btn-sm' onclick='addRelayRow()'>➕ Add Relay</button>"
      "<button class='btn btn-primary btn-sm' onclick='saveRelays()'>💾 Save Relays</button>"
      "<button class='btn btn-danger btn-sm' onclick='allRelaysOff()'>🔴 All OFF</button>"
      "<button class='btn btn-success btn-sm' onclick='allRelaysOn()'>🟢 All ON</button>"
    "</div>"
    "<div id='relay-save-msg'></div>"
  "</div>"

  "<div class='form-section' style='margin-top:20px'>"
    "<h3>⚙️ Sensors Configuration</h3>"
    "<div id='sensor-config-grid'>"
      "<!-- populated by JS -->"
    "</div>"
    "<div style='margin-top:16px;display:flex;gap:10px;flex-wrap:wrap'>"
      "<button class='btn btn-success btn-sm' onclick='addSensorRow()'>➕ Add Sensor</button>"
      "<button class='btn btn-primary btn-sm' onclick='saveSensors()'>💾 Save Sensors</button>"
    "</div>"
    "<div id='sensors-save-msg' style='margin-top:8px'></div>"
  "</div>"

  "<div class='form-section' style='margin-top:20px'>"
    "<h3>🏷️ Device Identity</h3>"
    "<div class='form-row'>"
      "<div><label>Serial Number</label><input id='dev-serial' maxlength='7' placeholder='0000001' "
        "style='font-family:monospace'/></div>"
      "<div><label>Firmware</label><input id='dev-fw' readonly style='font-family:monospace;opacity:.8'/></div>"
    "</div>"
    "<p style='font-size:.78rem;color:var(--muted);margin-top:6px'>"
      "Shown in the QR code as KX-XXXXXXXX. Use a sequential number per unit (e.g. 0000001)."
    "</p>"
    "<button class='btn btn-primary btn-sm' onclick='saveSerial()'>💾 Save Serial</button>"
    "<div id='dev-serial-msg' style='margin-top:8px'></div>"
  "</div>"

  "<div class='form-section' style='margin-top:20px'>"
    "<h3>🔍 Modbus Network Scanner</h3>"
    "<p style='font-size:.78rem;color:var(--muted);margin-bottom:14px'>"
      "Scans Modbus IDs 1 to 247 on the RS485 bus to automatically detect connected sensors."
    "</p>"
    "<div style='display:flex;align-items:center;gap:12px;margin-bottom:16px'>"
      "<button class='btn btn-primary btn-sm' id='scan-btn' onclick='startModbusScan()'>🔍 Scan Network</button>"
      "<div id='scan-progress-container' style='flex-grow:1;display:none;background:var(--border);height:10px;border-radius:5px;overflow:hidden;min-width:150px'>"
        "<div id='scan-progress-bar' style='background:var(--green);width:0%;height:100%;transition:width 0.1s'></div>"
      "</div>"
      "<span id='scan-status-lbl' style='font-size:.85rem;font-weight:600'></span>"
    "</div>"
    "<div id='scan-results-container' style='display:none'>"
      "<h4>Discovered Devices</h4>"
      "<div style='overflow-x:auto'>"
        "<table style='width:100%;border-collapse:collapse;margin-top:8px'>"
          "<thead>"
            "<tr style='border-bottom:2px solid var(--border);text-align:left;font-size:.85rem'>"
              "<th style='padding:8px'>Add</th>"
              "<th style='padding:8px'>Modbus ID</th>"
              "<th style='padding:8px'>Device Type</th>"
            "</tr>"
          "</thead>"
          "<tbody id='scan-results-body'>"
          "</tbody>"
        "</table>"
      "</div>"
      "<div style='margin-top:12px;display:flex;gap:10px'>"
        "<button class='btn btn-success btn-sm' onclick='applySelectedScan()'>✅ Apply Selected</button>"
        "<button class='btn btn-danger btn-sm' onclick='clearScanSelection()'>✖ Clear</button>"
      "</div>"
      "<div id='scan-apply-msg' style='margin-top:8px'></div>"
    "</div>"
  "</div>"
"</div>"

/* ============ PAGE: MQTT ============ */
"<div class='page' id='page-mqtt'>"
  "<div class='form-section'>"
    "<h3>Cloud MQTT Provisioning</h3>"
    "<div class='form-row'>"
      "<div><label>Broker Host / IP</label><input id='mqtt-broker' placeholder='mqtt.example.com'/></div>"
      "<div><label>Port</label><input id='mqtt-port' type='number' value='1883'/></div>"
    "</div>"
    "<div class='form-row'>"
      "<div><label>Client ID</label><input id='mqtt-client' placeholder='kontrx-gateway-01'/></div>"
      "<div><label>Username</label><input id='mqtt-user' placeholder='(optional)'/></div>"
      "<div><label>Password</label><input id='mqtt-pass' type='password' placeholder='(optional)'/></div>"
    "</div>"
    "<button class='btn btn-primary' onclick='saveMQTT()'>☁️ Save &amp; Connect</button>"
    "<div id='mqtt-msg'></div>"
  "</div>"
"</div>"

/* ============ PAGE: OTA ============ */
"<div class='page' id='page-ota'>"
  "<div class='form-section' id='ota-upload-panel'>"
    "<h3>📦 Firmware Upload</h3>"
    "<p style='font-size:.78rem;color:var(--muted);margin-bottom:14px'>"
      "Select the Kontrx.bin firmware file. The device will write it to the staging flash area,"
      "verify CRC, and reboot into the bootloader for automatic swap."
    "</p>"
    "<div style='background:rgba(5,10,20,.6);border:2px dashed var(--border);border-radius:12px;"
      "padding:30px;text-align:center;margin-bottom:16px' id='drop-zone'"
      "ondragover='event.preventDefault()' ondrop='handleDrop(event)'>"
      "<div style='font-size:2rem;margin-bottom:8px'>📁</div>"
      "<div style='font-size:.85rem;color:var(--muted)'>Drag &amp; Drop Kontrx.bin here, or</div>"
      "<label class='btn btn-primary' style='margin-top:10px;display:inline-flex;cursor:pointer'>"
        "🗂 Choose File<input type='file' id='fw-file' accept='.bin' style='display:none' onchange='fileSelected()'>"
      "</label>"
      "<div id='fw-name' style='font-size:.75rem;color:var(--accent);margin-top:8px'></div>"
    "</div>"
    "<div class='progress-wrap'><div class='progress-bar' id='ota-bar'></div></div>"
    "<div id='ota-pct' style='font-size:.75rem;color:var(--muted);text-align:center;margin-bottom:12px'>Awaiting file...</div>"
    "<button class='btn btn-success' id='btn-flash' onclick='uploadFirmware()' disabled>⚡ Flash Firmware</button>"
    "<div id='ota-msg'></div>"
  "</div>"
"</div>"

"</div>"
/* ============ SCRIPTS ============ */
"<script>"

/* ----- State ----- */
"var otpUnlocked=true;"
"var portOpts=['A','B','C','D','E'];"
"var statusTimer=null;"
"var uptimeTimer=null;"
"var relays=[];"        /* dynamic: {id,name,pin,nc,state} */
"var sensors=[];"       /* dynamic: {type,id} from config */
"var sensorValues={};"  /* live: 'type:id' -> {value,temp,valid} */
"var scanDevices=[];"   /* last scan results {id,type} */
"var lastSensorSig='';"
"var lastRelaySig='';"
"var sensorTypeNames={ph:'pH',orp:'ORP',ec:'EC',do:'DO',ammonia:'Ammonia',ultrasonic:'Ultrasonic',multi_us:'Multi-US'};"
"var sensorTypeUnits={ph:'pH',orp:'mV',ec:'mS/cm',do:'mg/L',ammonia:'mg/L',ultrasonic:'mm',multi_us:'mm'};"
"var fmtF=function(v){return(v==null||v<=-900)?'--':v.toFixed(2);};"
"var fmtI=function(v){return(v==null||v<=-900)?'--':Math.round(v);};"

/* ----- Tab Navigation ----- */
"function showTab(t){"
  "document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));"
  "document.querySelectorAll('.tab').forEach(b=>b.classList.remove('active'));"
  "document.getElementById('page-'+t).classList.add('active');"
  "event.currentTarget.classList.add('active');"
"}"

/* ----- Relay status grid (dynamic) ----- */
"function buildRelayStatusGrid(){"
  "var g=document.getElementById('relay-status-grid');if(!g)return;"
  "g.innerHTML='';"
  "for(var i=0;i<relays.length;i++){"
    "var r=relays[i];"
    "var d=document.createElement('div');"
    "d.className='relay-btn '+(r.state?'on':'off');"
    "d.id='rsb-'+i;"
    "d.innerHTML='<div class=\"relay-led\"></div>'+"
      "'<div class=\"relay-name\">'+(r.name||('R'+(i+1)))+'</div>'+"
      "'<div class=\"relay-pin\">'+r.pin+'</div>'+"
      "'<div class=\"relay-nc\">'+(r.nc?'NC':'NO')+'</div>';"
    "d.onclick=(function(idx){return function(){toggleRelay(idx);};})(i);"
    "g.appendChild(d);"
  "}"
"}"
/* ----- Relay config grid (dynamic) ----- */
"function buildRelayConfigGrid(){"
  "var g=document.getElementById('relay-config-grid');if(!g)return;"
  "if(!relays.length){g.innerHTML='<div style=\"color:var(--muted);font-size:.85rem\">No relays configured. Click “Add Relay”.</div>';return;}"
  "g.innerHTML='';"
  "for(var i=0;i<relays.length;i++){"
    "var r=relays[i];"
    "var row=document.createElement('div');"
    "row.style='display:grid;grid-template-columns:34px 1fr 1fr 150px 110px 120px 70px;gap:10px;align-items:center;padding:10px 0;border-bottom:1px solid rgba(30,58,95,.4)';"
    "row.innerHTML="
      "'<div style=\"font-size:.8rem;font-weight:700;color:var(--accent)\">R'+(i+1)+'</div>'+"
      "'<div><label>Name</label><input id=\"rcf-name-'+i+'\" style=\"padding:8px 10px;font-weight:600\" value=\"'+(r.name||('R'+(i+1)))+'\"/></div>'+"
      "'<div><label>Pin</label><input id=\"rcf-pin-'+i+'\" style=\"padding:8px 10px;text-transform:uppercase;font-weight:700\" value=\"'+r.pin+'\"/></div>'+"
      "'<div><label>Mode</label><select id=\"rcf-nc-'+i+'\" style=\"padding:8px 10px;min-width:140px;font-weight:600\">'+"
        "'<option value=\"0\"'+(r.nc==0?' selected':'')+'>NO (Normal Open)</option>'+"
        "'<option value=\"1\"'+(r.nc==1?' selected':'')+'>NC (Normal Closed)</option>'+"
      "'</select></div>'+"
      "'<div><label>Current</label>'+"
        "'<button id=\"rtgl-btn-'+i+'\" class=\"btn btn-sm '+(r.state?'btn-success':'btn-danger')+'\" onclick=\"toggleRelay('+i+')\">'+"
          "'<span id=\"rtgl-'+i+'\">'+(r.state?'ON':'OFF')+'</span></button>'+"
      "'</div>'+"
      "'<div><label>Status</label>'+"
        "'<div id=\"rcf-status-'+i+'\" style=\"display:flex;align-items:center;height:32px;font-size:.7rem;color:var(--muted)\">✓ Loaded</div>'+"
      "'</div>'+"
      "'<div style=\"text-align:right\">'+"
        "'<button class=\"btn btn-danger btn-sm\" onclick=\"deleteRelayRow('+i+')\">🗑</button>'+"
      "'</div>';"
    "g.appendChild(row);"
  "}"
"}"
"function addRelayRow(){"
  "if(relays.length>=16){showMsg('relay-save-msg','Maximum 16 relays reached.','warn');return;}"
  "var used={};for(var i=0;i<relays.length;i++)used[relays[i].pin]=1;"
  "var pin='PE2';var found=false;"
  "for(var p=0;p<5&&!found;p++)for(var n=0;n<=15&&!found;n++){"
    "var cand='P'+portOpts[p]+n;"
    "if(!used[cand]&&!RESERVED_PINS[cand]){pin=cand;found=true;}"
  "}"
  "relays.push({id:relays.length,name:'Relay'+(relays.length+1),pin:pin,nc:0,state:0});"
  "buildRelayConfigGrid();buildRelayStatusGrid();"
  "showMsg('relay-save-msg','Relay added. Click Save Relays to persist.','warn');"
"}"
"function deleteRelayRow(i){"
  "relays.splice(i,1);"
  "for(var j=i;j<relays.length;j++)relays[j].id=j;"
  "buildRelayConfigGrid();buildRelayStatusGrid();"
  "showMsg('relay-save-msg','Relay removed. Click Save Relays to persist.','warn');"
"}"
"function validateRelays(){"
  "var used={};"
  "for(var i=0;i<relays.length;i++){"
    "var el=document.getElementById('rcf-pin-'+i);"
    "var raw=el?el.value.trim().toUpperCase():relays[i].pin;"
    "var match=raw.match(/^P?([A-E])([0-9]{1,2})$/);"
    "if(!match)return {ok:false,msg:'R'+(i+1)+' has invalid pin format (e.g. PE2, PC12, A0)'};"
    "var port=match[1];var pin=parseInt(match[2]);"
    "if(pin<0||pin>15)return {ok:false,msg:'R'+(i+1)+' pin number must be 0 to 15'};"
    "var formatted='P'+port+pin;"
    "if(RESERVED_PINS[formatted])return {ok:false,msg:'Pin '+formatted+' is reserved for '+RESERVED_PINS[formatted]};"
    "if(used[formatted]!=null)return {ok:false,msg:'Pin '+formatted+' is assigned to both R'+(used[formatted]+1)+' and R'+(i+1)};"
    "used[formatted]=i;"
  "}"
  "return {ok:true};"
"}"
"function saveRelays(){"
  "var v=validateRelays();"
  "if(!v.ok){showMsg('relay-save-msg',v.msg,'err');return;}"
  "var payload=[];"
  "for(var i=0;i<relays.length;i++){"
    "var nameEl=document.getElementById('rcf-name-'+i);"
    "var pinEl=document.getElementById('rcf-pin-'+i);"
    "var ncEl=document.getElementById('rcf-nc-'+i);"
    "var name=nameEl?(nameEl.value.trim()||('Relay'+(i+1))):('Relay'+(i+1));"
    "var pin=pinEl?pinEl.value.trim().toUpperCase():relays[i].pin;"
    "var nc=ncEl?parseInt(ncEl.value):relays[i].nc;"
    "payload.push({name:name,pin:pin,nc:nc});"
  "}"
  "fetch('/api/config/relays',{method:'POST',"
    "headers:{'Content-Type':'application/json'},"
    "body:JSON.stringify({relays:payload})})"
  ".then(r=>r.json()).then(d=>{"
    "if(d.ok){showMsg('relay-save-msg','✓ Relay config saved','ok');fetchStatus();}"
    "else{showMsg('relay-save-msg',d.error||'Save failed','err');}"
  "}).catch(function(){"
    "showMsg('relay-save-msg','Save failed.','err');"
  "});"
"}"
"function updateRelayConfigStates(){"
  "for(var i=0;i<relays.length;i++){"
    "var btn=document.getElementById('rtgl-btn-'+i);"
    "var txt=document.getElementById('rtgl-'+i);"
    "if(btn&&txt){"
      "btn.className='btn btn-sm '+(relays[i].state?'btn-success':'btn-danger');"
      "txt.textContent=relays[i].state?'ON':'OFF';"
    "}"
  "}"
"}"


"function toggleRelay(i){"
  "fetch('/api/relay?id='+i+'&state='+(relays[i].state?0:1),{method:'POST'})"
  ".then(r=>r.json()).then(d=>{"
    "relays[i].state=d.state;"
    "buildRelayStatusGrid();"
    "updateRelayConfigStates();"
  "}).catch(()=>{});"
"}"

"function allRelaysOff(){"
  "fetch('/api/relay/all?state=0',{method:'POST'}).then(()=>fetchStatus());"
"}"
"function allRelaysOn(){"
  "fetch('/api/relay/all?state=1',{method:'POST'}).then(()=>fetchStatus());"
"}"

"var RESERVED_PINS={"
  "'PA6':'LED Indicator',"
  "'PA9':'USART1 Debug Console (TX)',"
  "'PA10':'USART1 Debug Console (RX)',"
  "'PB10':'USART3 Modbus RTU (TX)',"
  "'PB11':'USART3 Modbus RTU (RX)',"
  "'PB12':'SPI2 W5500 Ethernet (CS)',"
  "'PB13':'SPI2 W5500 Ethernet (SCK)',"
  "'PB14':'SPI2 W5500 Ethernet (MISO)',"
  "'PB15':'SPI2 W5500 Ethernet (MOSI)',"
  "'PD2':'MAX485 Driver (RE Control)',"
  "'PD3':'MAX485 Driver (DE Control)'"
"};"


"function saveMQTT(){"
  "var payload={"
    "broker:document.getElementById('mqtt-broker').value,"
    "port:parseInt(document.getElementById('mqtt-port').value)||1883,"
    "client_id:document.getElementById('mqtt-client').value,"
    "username:document.getElementById('mqtt-user').value,"
    "password:document.getElementById('mqtt-pass').value"
  "};"
  "fetch('/api/config/mqtt',{method:'POST',"
    "headers:{'Content-Type':'application/json'},"
    "body:JSON.stringify(payload)})"
  ".then(r=>r.json())"
  ".then(d=>showMsg('mqtt-msg','MQTT config saved!','ok'))"
  ".catch(()=>showMsg('mqtt-msg','Save failed.','err'));"
"}"
"function saveSerial(){"
  "var raw=document.getElementById('dev-serial').value.replace(/\\D/g,'');"
  "var n=parseInt(raw||'0',10);"
  "if(!n||n>9999999){showMsg('dev-serial-msg','Serial must be 1..9999999.','warn');return;}"
  "document.getElementById('dev-serial').value=('0000000'+n).slice(-7);"
  "fetch('/api/config/serial',{method:'POST',"
    "headers:{'Content-Type':'application/json'},"
    "body:JSON.stringify({serial:n})})"
  ".then(r=>r.json())"
  ".then(d=>showMsg('dev-serial-msg','Serial saved: KX-'+('0000000'+n).slice(-7),'ok'))"
  ".catch(()=>showMsg('dev-serial-msg','Save failed.','err'));"
"}"

/* ----- Sensor value cards (dynamic) ----- */
"function buildSensorCards(){"
  "var g=document.getElementById('sensor-cards');if(!g)return;"
  "var dyn=document.querySelectorAll('#sensor-cards .dyn-card');"
  "for(var i=0;i<dyn.length;i++)dyn[i].parentNode.removeChild(dyn[i]);"
  "for(var i=0;i<sensors.length;i++){"
    "var s=sensors[i];"
    "if(s.type==='multi_us')continue;"
    "var v=sensorValues[s.type+':'+s.id];"
    "var val=v&&v.valid?v.value:null;"
    "var tmp=v&&v.valid?v.temp:null;"
    "var unit=sensorTypeUnits[s.type]||'';"
    "var name=sensorTypeNames[s.type]||s.type;"
    "var card=document.createElement('div');"
    "card.className='card dyn-card';"
    "card.innerHTML='<div class=\"card-title\">'+(name+' #'+s.id)+'</div>'+"
      "'<div><span class=\"card-val\">'+(val!=null?fmtF(val):'--')+'</span><span class=\"card-unit\">'+unit+'</span></div>'+"
      "'<div class=\"card-sub\">Temp: '+(tmp!=null?fmtF(tmp):'--')+' °C</div>';"
    "g.appendChild(card);"
  "}"
"}"
"function buildMultiUSCards(mus){"
  "var g=document.getElementById('sensor-cards');if(!g)return;"
  "if(!mus||!mus.length)return;"
  "for(var i=0;i<mus.length;i++){"
    "var m=mus[i];"
    "var card=document.createElement('div');"
    "card.className='card dyn-card';"
    "card.style.gridColumn='span 2';"
    "var dist='';"
    "for(var k=0;k<8;k++)dist+='<div>US'+(k+1)+': '+(m.dist[k]>-900?fmtI(m.dist[k]):'--')+'mm</div>';"
    "card.innerHTML='<div class=\"card-title\">🔊 Multi-US Board #'+m.id+'</div>'+"
      "'<div class=\"multi-us-grid\">'+dist+'</div>'+"
      "'<div class=\"card-sub\">Avg: '+(m.avg>-900?fmtI(m.avg):'--')+'mm &nbsp; Comp: '+(m.comp>-900?fmtI(m.comp):'--')+'mm &nbsp; Temp: '+(m.temp>-900?fmtF(m.temp):'--')+'°C</div>';"
    "g.appendChild(card);"
  "}"
"}"
/* ----- Sensor config grid (dynamic) ----- */
"var sensorRowTypes=[['ph','pH'],['orp','ORP'],['ec','EC'],['do','DO'],['ammonia','Ammonia'],['ultrasonic','Ultrasonic'],['multi_us','Multi-US']];"
"function buildSensorConfigGrid(){"
  "var g=document.getElementById('sensor-config-grid');if(!g)return;"
  "if(!sensors.length){g.innerHTML='<div style=\"color:var(--muted);font-size:.85rem\">No sensors configured. Click “Add Sensor” or use Auto-Scan.</div>';return;}"
  "g.innerHTML='';"
  "for(var i=0;i<sensors.length;i++){"
    "var s=sensors[i];"
    "var row=document.createElement('div');"
    "row.style='display:grid;grid-template-columns:34px 1fr 120px 1fr 60px;gap:10px;align-items:center;padding:10px 0;border-bottom:1px solid rgba(30,58,95,.4)';"
    "var opts='';"
    "for(var t=0;t<sensorRowTypes.length;t++){"
      "opts+='<option value=\"'+sensorRowTypes[t][0]+'\"'+(sensorRowTypes[t][0]===s.type?' selected':'')+'>'+sensorRowTypes[t][1]+'</option>';"
    "}"
    "var vv=sensorValues[s.type+':'+s.id];"
    "var live=vv&&vv.valid?'<span class=\"card-val\" style=\"font-size:1rem\">'+vv.value+'</span>':'<span style=\"color:var(--muted)\">—</span>';"
    "row.innerHTML="
      "'<div style=\"font-size:.8rem;font-weight:700;color:var(--accent)\">S'+(i+1)+'</div>'+"
      "'<div><label>Type</label><select id=\"scfg-type-'+i+'\" style=\"padding:8px 10px;font-weight:600\" onchange=\"onSensorRowChange('+i+')\">'+opts+'</select></div>'+"
      "'<div><label>Modbus ID</label><input id=\"scfg-id-'+i+'\" type=\"number\" min=\"1\" max=\"247\" style=\"padding:8px 10px;font-weight:700\" value=\"'+s.id+'\" onchange=\"onSensorRowChange('+i+')\"/></div>'+"
      "'<div><label>Live</label>'+live+'</div>'+"
      "'<div style=\"text-align:right\"><button class=\"btn btn-danger btn-sm\" onclick=\"deleteSensorRow('+i+')\">?</button></div>';"
    "g.appendChild(row);"
  "}"
"}"
"function addSensorRow(){"
  "if(sensors.length>=16){showMsg('sensors-save-msg','Maximum 16 sensors reached.','warn');return;}"
  "var used={};for(var i=0;i<sensors.length;i++)used[sensors[i].id]=1;"
  "var id=1;while(used[id]&&id<=247)id++;"
  "sensors.push({type:'ph',id:id});"
  "buildSensorConfigGrid();"
  "showMsg('sensors-save-msg','Sensor added. Click Save Sensors to persist.','warn');"
"}"
"function deleteSensorRow(i){"
  "sensors.splice(i,1);"
  "buildSensorConfigGrid();"
  "showMsg('sensors-save-msg','Sensor removed. Click Save Sensors to persist.','warn');"
"}"
"function onSensorRowChange(i){"
  "var tEl=document.getElementById('scfg-type-'+i);"
  "var idEl=document.getElementById('scfg-id-'+i);"
  "if(!tEl||!idEl)return;"
  "sensors[i].type=tEl.value;"
  "sensors[i].id=parseInt(idEl.value)||1;"
"}"
"function saveSensors(){"
  "var used={};"
  "for(var i=0;i<sensors.length;i++){"
    "if(!sensors[i].type){showMsg('sensors-save-msg','Sensor '+(i+1)+' has no type','err');return;}"
    "var id=sensors[i].id;"
    "if(id<1||id>247){showMsg('sensors-save-msg','Sensor '+(i+1)+' id must be 1..247','err');return;}"
    "if(used[id]!=null){showMsg('sensors-save-msg','Modbus id '+id+' is assigned twice','err');return;}"
    "used[id]=i;"
  "}"
  "fetch('/api/config/sensors',{method:'POST',"
    "headers:{'Content-Type':'application/json'},"
    "body:JSON.stringify({sensors:sensors.map(function(s){return {type:s.type,id:s.id};})})})"
  ".then(r=>r.json()).then(d=>{"
    "if(d.ok){showMsg('sensors-save-msg','✓ Sensor config saved','ok');fetchStatus();}"
    "else{showMsg('sensors-save-msg',d.error||'Save failed','err');}"
  "}).catch(()=>{});"
"}"

"var scanTimer=null;"
"function startModbusScan(){"
  "var btn=document.getElementById('scan-btn');"
  "btn.disabled=true;"
  "document.getElementById('scan-progress-container').style.display='block';"
  "document.getElementById('scan-results-container').style.display='none';"
  "document.getElementById('scan-status-lbl').textContent='Starting scan...';"
  "document.getElementById('scan-progress-bar').style.width='0%';"
  
  "fetch('/api/modbus/scan',{method:'POST'})"
  ".then(()=>{"
    "scanTimer=setInterval(pollScanStatus,500);"
  "});"
"}"

"function pollScanStatus(){"
  "fetch('/api/modbus/scan')"
  ".then(r=>r.json())"
  ".then(d=>{"
    "document.getElementById('scan-progress-bar').style.width=d.progress+'%';"
    "document.getElementById('scan-status-lbl').textContent=d.progress+'%';"
    "if(d.scanning===false){"
      "clearInterval(scanTimer);"
      "document.getElementById('scan-btn').disabled=false;"
      "document.getElementById('scan-status-lbl').textContent='Scan complete!';"
      "displayScanResults(d.devices);"
    "}"
  "}).catch(()=>{"
    "clearInterval(scanTimer);"
    "document.getElementById('scan-btn').disabled=false;"
  "});"
"}"

"function displayScanResults(devs){"
  "scanDevices=devs||[];"
  "var body=document.getElementById('scan-results-body');"
  "body.innerHTML='';"
  "document.getElementById('scan-results-container').style.display='block';"
  "document.getElementById('scan-apply-msg').textContent='';"
  "if(!scanDevices.length){"
    "body.innerHTML='<tr><td colspan=\"3\" style=\"padding:8px;text-align:center;color:var(--muted)\">No devices found.</td></tr>';"
    "return;"
  "}"
  "var types=['?','pH','ORP','EC','DO','Ammonia','Ultrasonic','Multi-US'];"
  "scanDevices.forEach(function(dev,idx){"
    "var tr=document.createElement('tr');"
    "tr.style.borderBottom='1px solid var(--border)';"
    "var name=types[dev.type]||('Type '+dev.type);"
    "tr.innerHTML='<td style=\"padding:8px\"><input type=\"checkbox\" data-idx=\"'+idx+'\"></td>'+"
      "'<td style=\"padding:8px;font-weight:600\">'+dev.id+'</td>'+"
      "'<td style=\"padding:8px\">'+name+'</td>';"
    "body.appendChild(tr);"
  "});"
"}"
"function applySelectedScan(){"
  "var added=0;var skipped=0;"
  "var used={};"
  "for(var i=0;i<sensors.length;i++)used[sensors[i].id]=1;"
  "var boxes=document.querySelectorAll('#scan-results-body input[type=checkbox]:checked');"
  "for(var j=0;j<boxes.length;j++){"
    "var idx=parseInt(boxes[j].getAttribute('data-idx'));"
    "var dev=scanDevices[idx];"
    "if(!dev||dev.type<1||dev.type>7){skipped++;continue;}"
    "if(used[dev.id]){skipped++;continue;}"
    "if(sensors.length>=16){showMsg('scan-apply-msg','Maximum 16 sensors reached.','warn');break;}"
    "var typeName=sensorRowTypes[dev.type-1][0];"
    "sensors.push({type:typeName,id:dev.id});"
    "used[dev.id]=1;added++;"
  "}"
  "if(added){"
    "buildSensorConfigGrid();"
    "showMsg('scan-apply-msg','✓ Added '+added+' sensor(s). Click Save Sensors to persist.','ok');"
  "}else{"
    "showMsg('scan-apply-msg','No new sensors added (already present or unsupported type).','warn');"
  "}"
"}"
"function clearScanSelection(){"
  "var boxes=document.querySelectorAll('#scan-results-body input[type=checkbox]');"
  "for(var i=0;i<boxes.length;i++)boxes[i].checked=false;"
"}"

"function fetchStatus(){"
  "var ctrl=new AbortController();"
  "var tid=setTimeout(function(){ctrl.abort();},3000);"
  "fetch('/api/status',{signal:ctrl.signal})"
  ".then(function(r){clearTimeout(tid);return r.json();})"
  ".then(function(d){"
    "var sig='';"
    "if(d.sensors){"
      "sensorValues={};"
      "var newSensors=[];"
      "for(var si=0;si<d.sensors.length;si++){"
        "var so=d.sensors[si];"
        "newSensors.push({type:so.type,id:so.id});"
        "sensorValues[so.type+':'+so.id]={value:so.value,temp:so.temp,valid:so.valid};"
        "sig+=so.type+':'+so.id+';';"
      "}"
      "if(sig!==lastSensorSig){"
        "lastSensorSig=sig;"
        "sensors=newSensors;"
        "buildSensorConfigGrid();"
      "}"
    "}"
    "buildSensorCards();"
    "buildMultiUSCards(d.multi_us);"
    "if(d.relays){"
      "var rsig='';"
      "for(var ri=0;ri<d.relays.length;ri++){rsig+=d.relays[ri].pin+'|'+d.relays[ri].nc+'|'+d.relays[ri].name+';';}"
      "if(rsig!==lastRelaySig){"
        "lastRelaySig=rsig;"
        "relays=d.relays.slice();"
        "buildRelayConfigGrid();"
      "}else{"
        "for(var rj=0;rj<d.relays.length&&rj<relays.length;rj++)relays[rj].state=d.relays[rj].state;"
      "}"
      "buildRelayStatusGrid();"
      "updateRelayConfigStates();"
    "}"
    "if(typeof d.uptime_s==='number'){"
      "var us=d.uptime_s;"
      "var hu=Math.floor(us/3600);"
      "var mu=Math.floor((us%3600)/60);"
      "var su=us%60;"
      "document.getElementById('uptime-val').textContent="
        "(hu<10?'0':'')+hu+':'+(mu<10?'0':'')+mu+':'+(su<10?'0':'')+su;"
    "}"
    "if(d.serial&&document.getElementById('dev-serial')){"
      "var sn=String(d.serial).replace(/\\D/g,'').slice(-7);"
      "if(sn)document.getElementById('dev-serial').value=sn;"
    "}"
    "if(d.fw&&document.getElementById('dev-fw'))document.getElementById('dev-fw').value=d.fw;"
    "document.getElementById('conn-dot').style.background='var(--green)';"
    "document.getElementById('conn-lbl').textContent='Online';"
    "generateQR(d);"
  "})"
  ".catch(function(){"
    "clearTimeout(tid);"
    "document.getElementById('conn-dot').style.background='var(--red)';"
    "document.getElementById('conn-lbl').textContent='Offline';"
  "});"
"}"

"function startPolling(){"
  "setTimeout(function(){"
    "fetchStatus();"
    "statusTimer=setInterval(fetchStatus,1500);"
  "},2500);"
"}"

"var qrcode=(function(){"
  "var PAD0=0xEC,PAD1=0x11;"
  "function QRCode(t,e){this.typeNumber=t;this.errorCorrectionLevel=e;this.modules=null;this.moduleCount=0;this.dataList=[];}"
  "QRCode.prototype={"
    "addData:function(d){this.dataList.push({mode:4,data:d,getLength:function(){return this.data.length;},write:function(b){for(var i=0;i<this.data.length;i++)b.put(this.data.charCodeAt(i),8);}});},"
    "isDark:function(r,c){return this.modules[r][c];},"
    "getModuleCount:function(){return this.moduleCount;},"
    "make:function(){"
      "var t=1;"
      "for(t=1;t<41;t++){"
        "var b=QRRSBlock.getRSBlocks(t,this.errorCorrectionLevel),buf=new QRBitBuffer(),tot=0;"
        "for(var i=0;i<b.length;i++)tot+=b[i].dataCount;"
        "for(var i=0;i<this.dataList.length;i++){var d=this.dataList[i];buf.put(d.mode,4);buf.put(d.getLength(),QRUtil.getLengthInBits(d.mode,t));d.write(buf);}"
        "if(buf.getLengthInBits()<=tot*8)break;"
      "}"
      "this.typeNumber=t;this.makeImpl(false,this.getBestMaskPattern());"
    "},"
    "makeImpl:function(test,mask){"
      "this.moduleCount=this.typeNumber*4+17;"
      "this.modules=new Array(this.moduleCount);"
      "for(var r=0;r<this.moduleCount;r++){this.modules[r]=new Array(this.moduleCount);for(var c=0;c<this.moduleCount;c++)this.modules[r][c]=null;}"
      "this.setupPositionProbePattern(0,0);this.setupPositionProbePattern(this.moduleCount-7,0);this.setupPositionProbePattern(0,this.moduleCount-7);"
      "this.setupPositionAdjustPattern();this.setupTimingPattern();this.setupTypeInfo(test,mask);if(this.typeNumber>=7)this.setupTypeNumber(test);"
      "var data=QRCode.createData(this.typeNumber,this.errorCorrectionLevel,this.dataList);"
      "this.mapData(data,mask);"
    "},"
    "setupPositionProbePattern:function(row,col){"
      "for(var r=-1;r<=7;r++){"
        "if(row+r<=-1||this.moduleCount<=row+r)continue;"
        "for(var c=-1;c<=7;c++){"
          "if(col+c<=-1||this.moduleCount<=col+c)continue;"
          "this.modules[row+r][col+c]=(0<=r&&r<=6&&(c==0||c==6))||(0<=c&&c<=6&&(r==0||r==6))||(2<=r&&r<=4&&2<=c&&c<=4);"
        "}"
      "}"
    "},"
    "getBestMaskPattern:function(){"
      "var min=0,best=0;"
      "for(var i=0;i<8;i++){this.makeImpl(true,i);var p=QRUtil.getLostPoint(this);if(i==0||min>p){min=p;best=i;}}"
      "return best;"
    "},"
    "setupTimingPattern:function(){"
      "for(var r=8;r<this.moduleCount-8;r++){if(this.modules[r][6]!=null)continue;this.modules[r][6]=(r%2==0);}"
      "for(var c=8;c<this.moduleCount-8;c++){if(this.modules[6][c]!=null)continue;this.modules[6][c]=(c%2==0);}"
    "},"
    "setupPositionAdjustPattern:function(){"
      "var pos=QRUtil.getPatternPosition(this.typeNumber);"
      "for(var i=0;i<pos.length;i++)for(var j=0;j<pos.length;j++){"
        "var row=pos[i],col=pos[j];if(this.modules[row][col]!=null)continue;"
        "for(var r=-2;r<=2;r++)for(var c=-2;c<=2;c++)this.modules[row+r][col+c]=(r==-2||r==2||c==-2||c==2||(r==0&&c==0));"
      "}"
    "},"
    "setupTypeInfo:function(test,mask){"
      "var bits=QRUtil.getBCHTypeInfo((this.errorCorrectionLevel<<3)|mask);"
      "for(var i=0;i<15;i++){"
        "var mod=(!test&&((bits>>i)&1)==1);"
        "if(i<6)this.modules[i][8]=mod;else if(i<8)this.modules[i+1][8]=mod;else this.modules[this.moduleCount-15+i][8]=mod;"
        "if(i<8)this.modules[8][this.moduleCount-i-1]=mod;else if(i<9)this.modules[8][15-i-1+1]=mod;else this.modules[8][15-i-1]=mod;"
      "}"
      "this.modules[this.moduleCount-8][8]=(!test);"
    "},"
    "setupTypeNumber:function(test){"
      "var bits=QRUtil.getBCHTypeNumber(this.typeNumber);"
      "for(var i=0;i<18;i++){var mod=(!test&&((bits>>i)&1)==1);this.modules[Math.floor(i/3)][i%3+this.moduleCount-8-3]=mod;}"
      "for(var i=0;i<18;i++){var mod=(!test&&((bits>>i)&1)==1);this.modules[i%3+this.moduleCount-8-3][Math.floor(i/3)]=mod;}"
    "},"
    "mapData:function(data,mask){"
      "var inc=-1,row=this.moduleCount-1,bitIndex=7,byteIndex=0;"
      "for(var col=this.moduleCount-1;col>0;col-=2){"
        "if(col==6)col--;"
        "while(true){"
          "for(var c=0;c<2;c++){"
            "if(this.modules[row][col-c]==null){"
              "var dark=(byteIndex<data.length)?(((data[byteIndex]>>>bitIndex)&1)==1):false;"
              "if(QRUtil.getMask(mask,row,col-c))dark=!dark;"
              "this.modules[row][col-c]=dark;bitIndex--;"
              "if(bitIndex==-1){byteIndex++;bitIndex=7;}"
            "}"
          "}"
          "row+=inc;if(row<0||this.moduleCount<=row){row-=inc;inc=-inc;break;}"
        "}"
      "}"
    "}"
  "};"
  "QRCode.createData=function(typeNumber,errorCorrectionLevel,dataList){"
    "var rsBlocks=QRRSBlock.getRSBlocks(typeNumber,errorCorrectionLevel),buffer=new QRBitBuffer();"
    "for(var i=0;i<dataList.length;i++){var d=dataList[i];buffer.put(d.mode,4);buffer.put(d.getLength(),QRUtil.getLengthInBits(d.mode,typeNumber));d.write(buffer);}"
    "var totalDataCount=0;for(var i=0;i<rsBlocks.length;i++)totalDataCount+=rsBlocks[i].dataCount;"
    "if(buffer.getLengthInBits()+4<=totalDataCount*8)buffer.put(0,4);"
    "while(buffer.getLengthInBits()%8!=0)buffer.putBit(false);"
    "while(true){if(buffer.getLengthInBits()>=totalDataCount*8)break;buffer.put(PAD0,8);if(buffer.getLengthInBits()>=totalDataCount*8)break;buffer.put(PAD1,8);}"
    "return QRCode.createBytes(buffer,rsBlocks);"
  "};"
  "QRCode.createBytes=function(buffer,rsBlocks){"
    "var offset=0,maxDc=0,maxEc=0,dcdata=new Array(rsBlocks.length),ecdata=new Array(rsBlocks.length);"
    "for(var r=0;r<rsBlocks.length;r++){"
      "var dcCount=rsBlocks[r].dataCount,ecCount=rsBlocks[r].totalCount-dcCount;"
      "maxDc=Math.max(maxDc,dcCount);maxEc=Math.max(maxEc,ecCount);"
      "dcdata[r]=new Array(dcCount);for(var i=0;i<dcdata[r].length;i++)dcdata[r][i]=0xff&buffer.buffer[i+offset];"
      "offset+=dcCount;"
      "var rsPoly=QRUtil.getErrorCorrectPolynomial(ecCount),rawPoly=new QRPolynomial(dcdata[r],rsPoly.getLength()-1);"
      "var modPoly=rawPoly.mod(rsPoly);ecdata[r]=new Array(rsPoly.getLength()-1);"
      "for(var i=0;i<ecdata[r].length;i++){var idx=i+modPoly.getLength()-ecdata[r].length;ecdata[r][i]=(idx>=0)?modPoly.get(idx):0;}"
    "}"
    "var totalCodeCount=0;for(var i=0;i<rsBlocks.length;i++)totalCodeCount+=rsBlocks[i].totalCount;"
    "var data=new Array(totalCodeCount),index=0;"
    "for(var i=0;i<maxDc;i++)for(var r=0;r<rsBlocks.length;r++)if(i<dcdata[r].length)data[index++]=dcdata[r][i];"
    "for(var i=0;i<maxEc;i++)for(var r=0;r<rsBlocks.length;r++)if(i<ecdata[r].length)data[index++]=ecdata[r][i];"
    "return data;"
  "};"
  "var QRUtil={"
    "PATTERN_POSITION_TABLE:[[],[6,18],[6,22],[6,26],[6,30],[6,34],[6,22,38],[6,24,42],[6,26,46],[6,28,50],[6,30,54],[6,32,58],[6,34,62],[6,26,46,66],[6,26,48,70],[6,26,50,74],[6,30,54,78],[6,30,56,82],[6,30,58,86],[6,34,62,90],[6,28,50,72,94],[6,26,50,74,98],[6,30,54,78,102],[6,28,54,80,106],[6,32,58,84,110],[6,30,58,86,114],[6,34,62,90,118],[6,26,50,74,98,122],[6,30,54,78,102,126],[6,26,52,78,104,130],[6,30,56,82,108,134],[6,34,60,86,112,138],[6,30,58,86,114,142],[6,34,62,90,118,146],[6,30,54,78,102,126,150],[6,24,50,76,102,128,154],[6,28,54,80,106,132,158],[6,32,58,84,110,136,162],[6,26,54,82,110,138,166],[6,30,58,86,114,142,170]],"
    "G15:(1<<10)|(1<<8)|(1<<5)|(1<<4)|(1<<2)|(1<<1)|(1<<0),G15_MASK:(1<<14)|(1<<12)|(1<<10)|(1<<4)|(1<<1),"
"G18:(1<<12)|(1<<11)|(1<<10)|(1<<9)|(1<<8)|(1<<5)|(1<<2)|(1<<0),"
    "getBCHTypeInfo:function(data){var d=data<<10;while(QRUtil.getBCHDigit(d)-QRUtil.getBCHDigit(QRUtil.G15)>=0)d^=(QRUtil.G15<<(QRUtil.getBCHDigit(d)-QRUtil.getBCHDigit(QRUtil.G15)));return((data<<10)|d)^QRUtil.G15_MASK;},"
"getBCHTypeNumber:function(data){var d=data<<12;while(QRUtil.getBCHDigit(d)-QRUtil.getBCHDigit(QRUtil.G18)>=0)d^=(QRUtil.G18<<(QRUtil.getBCHDigit(d)-QRUtil.getBCHDigit(QRUtil.G18)));return(data<<12)|d;},"
"getLengthInBits:function(mode,type){if(type<10){if(mode==1)return 10;if(mode==2)return 9;if(mode==4)return 8;if(mode==8)return 8;}else if(type<27){if(mode==1)return 12;if(mode==2)return 11;if(mode==4)return 16;if(mode==8)return 10;}if(mode==1)return 14;if(mode==2)return 13;if(mode==4)return 16;if(mode==8)return 12;},"
    "getBCHDigit:function(data){var digit=0;while(data!=0){digit++;data>>>=1;}return digit;},"
    "getPatternPosition:function(t){return QRUtil.PATTERN_POSITION_TABLE[t-1];},"
    "getMask:function(m,i,j){"
      "switch(m){"
        "case 0:return(i+j)%2==0;case 1:return i%2==0;case 2:return j%3==0;case 3:return(i+j)%3==0;"
        "case 4:return(Math.floor(i/2)+Math.floor(j/3))%2==0;case 5:return(i*j)%2+(i*j)%3==0;"
        "case 6:return((i*j)%2+(i*j)%3)%2==0;case 7:return((i*j)%3+(i+j)%2)%2==0;"
        "default:return false;"
      "}"
    "},"
    "getErrorCorrectPolynomial:function(len){var a=new QRPolynomial([1],0);for(var i=0;i<len;i++)a=a.multiply(new QRPolynomial([1,QRMath.gexp(i)],0));return a;},"
    "getLostPoint:function(qr){"
      "var mc=qr.getModuleCount(),lp=0;"
      "for(var row=0;row<mc;row++)for(var col=0;col<mc;col++){"
        "var same=0,dark=qr.isDark(row,col);"
        "for(var r=-1;r<=1;r++){if(row+r<0||mc<=row+r)continue;for(var c=-1;c<=1;c++){if(col+c<0||mc<=col+c)continue;if(r==0&&c==0)continue;if(dark==qr.isDark(row+r,col+c))same++;}}"
        "if(same>5)lp+=(3+same-5);"
      "}"
      "for(var row=0;row<mc-1;row++)for(var col=0;col<mc-1;col++){var count=0;if(qr.isDark(row,col))count++;if(qr.isDark(row+1,col))count++;if(qr.isDark(row,col+1))count++;if(qr.isDark(row+1,col+1))count++;if(count==0||count==4)lp+=3;}"
      "for(var row=0;row<mc;row++)for(var col=0;col<mc-6;col++){if(qr.isDark(row,col)&&!qr.isDark(row,col+1)&&qr.isDark(row,col+2)&&qr.isDark(row,col+3)&&qr.isDark(row,col+4)&&!qr.isDark(row,col+5)&&qr.isDark(row,col+6))lp+=40;}"
      "for(var col=0;col<mc;col++)for(var row=0;row<mc-6;row++){if(qr.isDark(row,col)&&!qr.isDark(row+1,col)&&qr.isDark(row+2,col)&&qr.isDark(row+3,col)&&qr.isDark(row+4,col)&&!qr.isDark(row+5,col)&&qr.isDark(row+6,col))lp+=40;}"
      "var darkCount=0;for(var col=0;col<mc;col++)for(var row=0;row<mc;row++)if(qr.isDark(row,col))darkCount++;"
      "var ratio=Math.abs(100*darkCount/mc/mc-50)/5;lp+=ratio*10;"
      "return lp;"
    "},"
  "};"
  "var QRMath={"
    "glog:function(n){return QRMath.LOG_TABLE[n];},"
    "gexp:function(n){while(n<0)n+=255;while(n>=255)n-=255;return QRMath.EXP_TABLE[n];},"
    "EXP_TABLE:new Array(256),LOG_TABLE:new Array(256)"
  "};"
  "for(var i=0;i<8;i++)QRMath.EXP_TABLE[i]=1<<i;"
  "for(var i=8;i<256;i++)QRMath.EXP_TABLE[i]=QRMath.EXP_TABLE[i-4]^QRMath.EXP_TABLE[i-5]^QRMath.EXP_TABLE[i-6]^QRMath.EXP_TABLE[i-8];"
  "for(var i=0;i<255;i++)QRMath.LOG_TABLE[QRMath.EXP_TABLE[i]]=i;"
  "function QRPolynomial(num,shift){"
    "var offset=0;while(offset<num.length&&num[offset]==0)offset++;"
    "this.num=new Array(num.length-offset+shift);for(var i=0;i<num.length-offset;i++)this.num[i]=num[i+offset];"
  "}"
  "QRPolynomial.prototype={"
    "get:function(i){return this.num[i];},getLength:function(){return this.num.length;},"
    "multiply:function(e){"
      "var num=new Array(this.getLength()+e.getLength()-1);"
      "for(var i=0;i<this.getLength();i++)for(var j=0;j<e.getLength();j++)num[i+j]^=QRMath.gexp(QRMath.glog(this.get(i))+QRMath.glog(e.get(j)));"
      "return new QRPolynomial(num,0);"
    "},"
    "mod:function(e){"
      "if(this.getLength()-e.getLength()<0)return this;"
      "var ratio=QRMath.glog(this.get(0))-QRMath.glog(e.get(0)),num=new Array(this.getLength());"
      "for(var i=0;i<this.getLength();i++)num[i]=this.get(i);"
      "for(var i=0;i<e.getLength();i++)num[i]^=QRMath.gexp(QRMath.glog(e.get(i))+ratio);"
      "return new QRPolynomial(num,0).mod(e);"
    "}"
  "};"
  "function QRRSBlock(t,d){this.totalCount=t;this.dataCount=d;}"
  "QRRSBlock.RS_BLOCK_TABLE=[[1,26,19],[1,26,16],[1,26,13],[1,26,9],[1,44,34],[1,44,28],[1,44,22],[1,44,16],[1,70,55],[1,70,44],[2,35,17],[2,35,13],[1,100,80],[2,50,32],[2,50,24],[4,25,9],[1,134,108],[2,67,43],[2,33,15,2,34,16],[2,33,11,2,34,12],[2,86,68],[4,43,27],[4,43,19],[4,43,15],[2,98,78],[4,49,31],[2,32,14,4,33,15],[4,39,13,1,40,14],[2,121,97],[2,60,38,2,61,39],[4,40,18,2,41,19],[4,40,14,2,41,15],[2,146,116],[3,58,36,2,59,37],[4,36,16,4,37,17],[4,36,12,4,37,13],[2,86,68,2,87,69],[4,69,43,1,70,44],[6,43,19,2,44,20],[6,43,15,2,44,16],[4,101,81],[1,80,50,4,81,51],[4,50,22,4,51,23],[3,36,12,8,37,13],[2,116,92,2,117,93],[6,58,36,2,59,37],[4,46,20,6,47,21],[7,42,14,4,43,15],[4,133,107],[8,59,37,1,60,38],[8,44,20,4,45,21],[12,33,11,4,34,12],[3,145,115,1,146,116],[4,64,40,5,65,41],[11,36,16,5,37,17],[11,36,12,5,37,13],[5,109,87,1,110,88],[5,65,41,5,66,42],[5,54,24,7,55,25],[11,36,12,7,37,13],[5,122,98,1,123,99],[7,73,45,3,74,46],[15,43,19,2,44,20],[3,45,15,13,46,16],[1,135,107,5,136,108],[10,74,46,1,75,47],[1,50,22,15,51,23],[2,42,14,17,43,15],[5,150,120,1,151,121],[9,69,43,4,70,44],[17,50,22,1,51,23],[2,42,14,19,43,15],[3,141,113,4,142,114],[3,70,44,11,71,45],[17,47,21,4,48,22],[9,39,13,16,40,14],[3,135,107,5,136,108],[3,67,41,13,68,42],[15,54,24,5,55,25],[15,43,15,10,44,16],[4,144,116,4,145,117],[17,68,42],[17,50,22,6,51,23],[19,46,16,6,47,17],[2,139,111,7,140,112],[17,74,46],[7,54,24,16,55,25],[34,37,13],[4,151,121,5,152,122],[4,75,47,14,76,48],[11,54,24,14,55,25],[16,45,15,14,46,16],[6,147,117,4,148,118],[6,73,45,14,74,46],[11,54,24,16,55,25],[30,46,16,2,47,17],[8,132,106,4,133,107],[8,75,47,13,76,48],[7,54,24,22,55,25],[22,45,15,13,46,16],[10,142,114,2,143,115],[19,74,46,4,75,47],[28,50,22,6,51,23],[33,46,16,4,47,17],[8,152,122,4,153,123],[22,73,45,3,74,46],[8,53,23,26,54,24],[12,45,15,28,46,16],[3,147,117,10,148,118],[3,73,45,23,74,46],[4,54,24,31,55,25],[11,45,15,31,46,16],[7,146,116,7,147,117],[21,73,45,7,74,46],[1,53,23,37,54,24],[19,45,15,26,46,16],[5,145,115,10,146,116],[19,75,47,10,76,48],[15,54,24,25,55,25],[23,45,15,25,46,16],[13,145,115,3,146,116],[2,74,46,29,75,47],[42,54,24,1,55,25],[23,45,15,28,46,16],[17,145,115],[10,74,46,23,75,47],[10,54,24,35,55,25],[19,45,15,35,46,16],[17,145,115,1,146,116],[14,74,46,21,75,47],[29,54,24,19,55,25],[11,45,15,46,46,16],[13,145,115,6,146,116],[14,74,46,23,75,47],[44,54,24,7,55,25],[59,46,16,1,47,17],[12,151,121,7,152,122],[12,75,47,26,76,48],[39,54,24,14,55,25],[22,45,15,41,46,16],[6,151,121,14,152,122],[6,75,47,34,76,48],[46,54,24,10,55,25],[2,45,15,64,46,16],[17,152,122,4,153,123],[29,74,46,14,75,47],[49,54,24,10,55,25],[24,45,15,46,46,16],[4,152,122,18,153,123],[13,74,46,32,75,47],[48,54,24,14,55,25],[42,45,15,32,46,16],[20,147,117,4,148,118],[40,75,47,7,76,48],[43,54,24,22,55,25],[10,45,15,67,46,16],[19,148,118,6,149,119],[18,75,47,31,76,48],[34,54,24,34,55,25],[20,45,15,61,46,16]];"
  "QRRSBlock.getRSBlocks=function(typeNumber,errorCorrectionLevel){"
    "var b=QRRSBlock.RS_BLOCK_TABLE[(typeNumber-1)*4+(errorCorrectionLevel==1?0:errorCorrectionLevel==0?1:errorCorrectionLevel==3?2:3)];"
    "var list=[];for(var i=0;i<b.length;i+=3)for(var j=0;j<b[i];j++)list.push(new QRRSBlock(b[i+1],b[i+2]));return list;"
  "};"
  "function QRBitBuffer(){this.buffer=[];this.length=0;}"
  "QRBitBuffer.prototype={"
    "put:function(num,len){for(var i=0;i<len;i++)this.putBit(((num>>>(len-i-1))&1)==1);},"
    "getLengthInBits:function(){return this.length;},"
    "putBit:function(bit){"
      "var bufIndex=Math.floor(this.length/8);"
      "if(this.buffer.length<=bufIndex)this.buffer.push(0);"
      "if(bit)this.buffer[bufIndex]|=(0x80>>>(this.length%8));"
      "this.length++;"
    "}"
  "};"
  "return QRCode;"
"})();"

"function generateQR(d){"
  "var mac=(d&&d.mac)||'00:08:DC:11:22:33';"
  "var ip=(d&&d.ip)||'192.168.1.200';"
  "var serial=(d&&d.serial)||'KX-0000001';"
  "var fw=(d&&d.fw)||'v1.0.1';"
  "var serialDigits=String(serial).replace(/\\D/g,'').slice(-7)||'0000001';"
  "var sarr=(d&&d.sensors)||[];"
  "var rel=(d&&d.relays)||[];"
  "var sensors=sarr.map(function(s){"
    "return {id:s.id,type:s.type,unit:(sensorTypeUnits[s.type]||''),name:((sensorTypeNames[s.type]||s.type)+' Sensor')};"
  "});"
  "var relays=rel.map(function(r){return {name:r.name,pin:r.pin,nc:r.nc};});"
  "var qrData={"
    "version:fw,"
    "type:'KONTRX-GATEWAY',"
    "serialNumber:serial,"
    "macAddress:mac,"
    "sparkplugEdgeNodeId:'kontrx-'+serialDigits,"
    "sparkplugDeviceId:'KontrxDevice-01',"
    "sensors:sensors,"
    "relays:relays"
  "};"
  "var text=JSON.stringify({qrData:qrData});"
  "document.getElementById('qr-label').textContent="
    "'Serial:'+serial+'|MAC:'+mac+'|IP:'+ip;"
  "try{"
    "var qr=new qrcode(0,1);"
    "qr.addData(text);"
    "qr.make();"
    "var count=qr.getModuleCount();"
    "var canvas=document.getElementById('qr-canvas');"
    "var ctx=canvas.getContext('2d');"
    "var size=canvas.width;"
    "var cellSize=Math.floor(size/(count+4));"
    "var margin=Math.floor((size-cellSize*count)/2);"
    "ctx.fillStyle='#ffffff';"
    "ctx.fillRect(0,0,size,size);"
    "ctx.fillStyle='#050a14';"
    "for(var r=0;r<count;r++)for(var c=0;c<count;c++){"
      "if(qr.isDark(r,c))ctx.fillRect(margin+c*cellSize,margin+r*cellSize,cellSize,cellSize);"
    "}"
  "}catch(e){console.error(e);}"
"}"

/* ----- File Selection ----- */
"function fileSelected(){"
  "var f=document.getElementById('fw-file').files[0];"
  "if(f){"
    "document.getElementById('fw-name').textContent=f.name+' ('+Math.round(f.size/1024)+' KB)';"
    "document.getElementById('btn-flash').disabled=false;"
  "}"
"}"
"function handleDrop(ev){"
  "ev.preventDefault();"
  "var f=ev.dataTransfer.files[0];"
  "if(f){document.getElementById('fw-file')._file=f;"
    "document.getElementById('fw-name').textContent=f.name+' ('+Math.round(f.size/1024)+' KB)';"
    "document.getElementById('btn-flash').disabled=false;"
  "}"
"}"

/* ----- OTA Upload ----- */
"function uploadFirmware(){"
  "var fi=document.getElementById('fw-file');"
  "var file=fi._file||fi.files[0];"
  "if(!file){showMsg('ota-msg','Select a firmware file first.','warn');return;}"
  "var btn=document.getElementById('btn-flash');"
  "btn.disabled=true;"
  "var bar=document.getElementById('ota-bar');"
  "var pct=document.getElementById('ota-pct');"
  "var xhr=new XMLHttpRequest();"
  "xhr.open('POST','/update',true);"
  "xhr.setRequestHeader('Content-Type','application/octet-stream');"
  "xhr.upload.onprogress=function(e){"
    "if(e.lengthComputable){"
      "var p=Math.round(e.loaded/e.total*100);"
      "bar.style.width=p+'%';"
      "pct.textContent='Uploading: '+p+'%';"
    "}"
  "};"
  "xhr.onreadystatechange=function(){"
    "if(xhr.readyState==4){"
      "if(xhr.status==200){"
        "bar.style.width='100%';"
        "pct.textContent='Upload complete!';"
        "showMsg('ota-msg','✅ Firmware received. Device rebooting into bootloader...','ok');"
      "}else{"
        "showMsg('ota-msg','❌ Upload failed: '+xhr.statusText,'err');"
        "btn.disabled=false;"
      "}"
    "}"
  "};"
  "xhr.send(file);"
"}"

/* ----- Alert helper ----- */
"function showMsg(id,txt,type){"
  "var el=document.getElementById(id);"
  "el.className='alert alert-'+type;"
  "el.textContent=txt;"
  "setTimeout(function(){el.textContent='';el.className='';},5000);"
"}"

/* ----- Init ----- */
"buildRelayStatusGrid();"
"buildRelayConfigGrid();"
"startPolling();"

"</script>"
"</body>"
"</html>";

#endif /* WEB_ASSETS_H */
