/**
 * @file    web_assets.h
 * @brief   Kontrx — Embedded SPA Web Assets (minified HTML/CSS/JS)
 *
 * Contains:
 *   KONTRX_HTML  — Full Single-Page Application stored as C string literal
 *
 * Pages/sections:
 *   #dashboard   — Live sensor values, relay states, uptime, QR code
 *   #relays      — Per-relay pin mapping and NO/NC state logic
 *   #mqtt        — MQTT broker provisioning
 *   #ota         — OTA firmware upload with OTP validation
 *
 * The SPA uses a tab-based layout (no page reload).
 * fetch('/api/status') polls every 1000 ms for live data.
 */

#ifndef WEB_ASSETS_H
#define WEB_ASSETS_H

#include <stddef.h>

/* ------------------------------------------------------------------ */
/*  The SPA is stored as a single const string literal.               */
/*  The HTTP server task prepends the HTTP/1.1 200 OK headers.        */
/* ------------------------------------------------------------------ */

static const char KONTRX_HTML[] =
"<!DOCTYPE html>"
"<html lang='en'>"
"<head>"
"<meta charset='UTF-8'>"
"<meta name='viewport' content='width=device-width,initial-scale=1'>"
"<title>Kontrx Edge Gateway</title>"
"<link href='https://fonts.googleapis.com/css2?family=Inter:wght@300;400;600;700;900&display=swap' rel='stylesheet'>"
"<style>"
":root{"
  "--bg:#050a14;--card:#0c1628;--card2:#111d35;--border:#1e3a5f;"
  "--accent:#00d4ff;--accent2:#7c3aed;--green:#10b981;--red:#ef4444;"
  "--yellow:#f59e0b;--text:#e2e8f0;--muted:#64748b;--font:'Inter',sans-serif;"
"}"
"*{box-sizing:border-box;margin:0;padding:0}"
"body{background:var(--bg);color:var(--text);font-family:var(--font);min-height:100vh;overflow-x:hidden}"
"body::before{"
  "content:'';position:fixed;top:-50%;left:-50%;width:200%;height:200%;"
  "background:radial-gradient(ellipse at 20% 20%,rgba(0,212,255,.06) 0%,transparent 50%),"
             "radial-gradient(ellipse at 80% 80%,rgba(124,58,237,.06) 0%,transparent 50%);"
  "pointer-events:none;z-index:0"
"}"
"#app{position:relative;z-index:1;max-width:1280px;margin:0 auto;padding:20px}"

/* --- Header --- */
".hdr{display:flex;align-items:center;justify-content:space-between;padding:18px 28px;"
  "background:linear-gradient(135deg,rgba(12,22,40,.9),rgba(17,29,53,.9));"
  "border:1px solid var(--border);border-radius:16px;margin-bottom:24px;"
  "backdrop-filter:blur(20px);box-shadow:0 0 40px rgba(0,212,255,.08)}"
".hdr-logo{display:flex;align-items:center;gap:14px}"
".hdr-logo svg{filter:drop-shadow(0 0 8px rgba(0,212,255,.6))}"
".hdr-title{font-size:1.5rem;font-weight:900;letter-spacing:-.02em;"
  "background:linear-gradient(135deg,#00d4ff,#7c3aed);-webkit-background-clip:text;-webkit-text-fill-color:transparent}"
".hdr-sub{font-size:.7rem;color:var(--muted);letter-spacing:.08em;text-transform:uppercase;margin-top:2px}"
".hdr-status{display:flex;align-items:center;gap:8px;font-size:.8rem;color:var(--muted)}"
".dot{width:8px;height:8px;border-radius:50%;background:var(--green);box-shadow:0 0 8px var(--green);animation:pulse 2s infinite}"
"@keyframes pulse{0%,100%{opacity:1}50%{opacity:.4}}"
".uptime{font-variant-numeric:tabular-nums;color:var(--accent)}"

/* --- Tabs --- */
".tabs{display:flex;gap:6px;margin-bottom:20px;background:rgba(12,22,40,.6);"
  "border:1px solid var(--border);border-radius:12px;padding:6px}"
".tab{flex:1;padding:10px 16px;border:none;cursor:pointer;border-radius:8px;"
  "font-family:var(--font);font-size:.8rem;font-weight:600;letter-spacing:.04em;"
  "text-transform:uppercase;color:var(--muted);background:transparent;transition:all .2s}"
".tab:hover{color:var(--text);background:rgba(30,58,95,.4)}"
".tab.active{color:var(--accent);background:rgba(0,212,255,.1);box-shadow:0 0 20px rgba(0,212,255,.15);border:1px solid rgba(0,212,255,.2)}"
".page{display:none}.page.active{display:block}"

/* --- Cards --- */
".grid{display:grid;gap:16px}"
".grid2{grid-template-columns:repeat(auto-fit,minmax(260px,1fr))}"
".grid3{grid-template-columns:repeat(auto-fit,minmax(200px,1fr))}"
".card{background:linear-gradient(135deg,var(--card),var(--card2));"
  "border:1px solid var(--border);border-radius:14px;padding:20px;"
  "position:relative;overflow:hidden;transition:transform .2s,box-shadow .2s}"
".card:hover{transform:translateY(-2px);box-shadow:0 8px 32px rgba(0,212,255,.1)}"
".card::before{content:'';position:absolute;top:0;left:0;right:0;height:2px;"
  "background:linear-gradient(90deg,var(--accent),var(--accent2));opacity:.4}"
".card-title{font-size:.65rem;text-transform:uppercase;letter-spacing:.12em;color:var(--muted);margin-bottom:10px}"
".card-val{font-size:2rem;font-weight:900;font-variant-numeric:tabular-nums;"
  "background:linear-gradient(135deg,var(--accent),#fff);-webkit-background-clip:text;-webkit-text-fill-color:transparent}"
".card-unit{font-size:.8rem;color:var(--muted);margin-left:4px;font-weight:400;-webkit-text-fill-color:var(--muted)}"
".card-sub{font-size:.75rem;color:var(--muted);margin-top:6px}"

/* --- Relay Grid --- */
".relay-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(120px,1fr));gap:12px}"
".multi-us-grid{display:grid;grid-template-columns:1fr 1fr;gap:4px 16px;font-size:.85rem;margin:6px 0}"
".relay-btn{background:var(--card2);border:1px solid var(--border);border-radius:10px;"
  "padding:14px;cursor:pointer;text-align:center;transition:all .2s;position:relative}"
".relay-btn.on{border-color:var(--green);background:rgba(16,185,129,.12);"
  "box-shadow:0 0 20px rgba(16,185,129,.2)}"
".relay-btn.on .relay-led{background:var(--green);box-shadow:0 0 10px var(--green)}"
".relay-btn.off .relay-led{background:var(--red);box-shadow:0 0 10px var(--red)}"
".relay-led{width:10px;height:10px;border-radius:50%;margin:0 auto 8px;transition:all .3s}"
".relay-name{font-size:.7rem;font-weight:700;letter-spacing:.05em;color:var(--text)}"
".relay-pin{font-size:.6rem;color:var(--muted);margin-top:2px}"
".relay-nc{font-size:.55rem;color:var(--yellow);margin-top:2px;font-weight:600}"

/* --- Config Forms --- */
".form-section{background:var(--card);border:1px solid var(--border);border-radius:14px;padding:24px;margin-bottom:16px}"
".form-section h3{font-size:.85rem;font-weight:700;color:var(--accent);text-transform:uppercase;letter-spacing:.08em;margin-bottom:16px}"
".form-row{display:grid;grid-template-columns:repeat(auto-fit,minmax(200px,1fr));gap:12px;margin-bottom:12px}"
"label{font-size:.72rem;color:var(--muted);display:block;margin-bottom:5px;letter-spacing:.04em;text-transform:uppercase}"
"input,select{width:100%;background:rgba(5,10,20,.6);border:1px solid var(--border);"
  "border-radius:8px;padding:10px 14px;color:var(--text);font-family:var(--font);font-size:.85rem;outline:none;transition:border-color .2s}"
"input:focus,select:focus{border-color:var(--accent);box-shadow:0 0 0 3px rgba(0,212,255,.1)}"
"select option{background:var(--card)}"

/* --- Buttons --- */
".btn{display:inline-flex;align-items:center;gap:8px;padding:10px 20px;border:none;"
  "border-radius:8px;font-family:var(--font);font-size:.82rem;font-weight:600;cursor:pointer;transition:all .2s}"
".btn-primary{background:linear-gradient(135deg,var(--accent),#0099cc);color:#000}"
".btn-primary:hover{transform:translateY(-1px);box-shadow:0 6px 20px rgba(0,212,255,.3)}"
".btn-danger{background:linear-gradient(135deg,var(--red),#c53030);color:#fff}"
".btn-danger:hover{box-shadow:0 6px 20px rgba(239,68,68,.3)}"
".btn-success{background:linear-gradient(135deg,var(--green),#059669);color:#fff}"
".btn-success:hover{box-shadow:0 6px 20px rgba(16,185,129,.3)}"
".btn-sm{padding:6px 14px;font-size:.75rem}"
".btn:disabled{opacity:.4;cursor:not-allowed;transform:none!important}"

/* --- Progress Bar --- */
".progress-wrap{background:rgba(5,10,20,.6);border-radius:999px;height:6px;overflow:hidden;margin:10px 0}"
".progress-bar{height:100%;border-radius:999px;background:linear-gradient(90deg,var(--accent),var(--accent2));"
  "transition:width .3s;width:0%}"

/* --- QR --- */
"#qr-container{display:flex;justify-content:center;padding:20px}"
"#qr-canvas{border-radius:12px;box-shadow:0 0 40px rgba(0,212,255,.2)}"

/* --- Alerts --- */
".alert{padding:12px 16px;border-radius:8px;font-size:.82rem;margin-top:10px}"
".alert-ok{background:rgba(16,185,129,.15);border:1px solid rgba(16,185,129,.4);color:var(--green)}"
".alert-err{background:rgba(239,68,68,.15);border:1px solid rgba(239,68,68,.4);color:var(--red)}"
".alert-warn{background:rgba(245,158,11,.15);border:1px solid rgba(245,158,11,.4);color:var(--yellow)}"
".hidden{display:none!important}"

/* --- OTP field --- */
".otp-wrap{display:flex;gap:8px;align-items:flex-end}"
".otp-wrap input{max-width:240px}"
"</style>"
"</head>"
"<body>"
"<div id='app'>"

/* ============ HEADER ============ */
"<div class='hdr'>"
  "<div class='hdr-logo'>"
    "<svg width='36' height='36' viewBox='0 0 36 36' fill='none'>"
      "<rect width='36' height='36' rx='8' fill='url(#g1)'/>"
      "<path d='M10 18h16M18 10v16' stroke='#000' stroke-width='2.5' stroke-linecap='round'/>"
      "<defs><linearGradient id='g1' x1='0' y1='0' x2='36' y2='36'>"
        "<stop stop-color='#00d4ff'/><stop offset='1' stop-color='#7c3aed'/>"
      "</linearGradient></defs>"
    "</svg>"
    "<div>"
      "<div class='hdr-title'>Kontrx</div>"
      "<div class='hdr-sub'>STM32F407 &nbsp;|&nbsp; Edge Gateway &nbsp;|&nbsp; FW v2.0.0</div>"
    "</div>"
  "</div>"
  "<div class='hdr-status'>"
    "<div class='dot' id='conn-dot'></div>"
    "<span id='conn-lbl'>Online</span>"
    "&nbsp;&nbsp;⏱&nbsp;<span class='uptime' id='uptime-val'>--:--:--</span>"
  "</div>"
"</div>"

/* ============ TABS ============ */
"<div class='tabs'>"
  "<button class='tab active' onclick='showTab(\"dashboard\")'>📊 Dashboard</button>"
  "<button class='tab' onclick='showTab(\"configs\")'>⚙️ Configs</button>"
  "<button class='tab' onclick='showTab(\"mqtt\")'>☁️ MQTT</button>"
  "<button class='tab' onclick='showTab(\"ota\")'>🔄 OTA Update</button>"
"</div>"

/* ============ PAGE: DASHBOARD ============ */
"<div class='page active' id='page-dashboard'>"
  "<div class='grid grid2' style='margin-bottom:16px'>"

    /* pH */
    "<div class='card'>"
      "<div class='card-title'>⚗️ pH Value</div>"
      "<div><span class='card-val' id='v-ph'>--</span><span class='card-unit'>pH</span></div>"
      "<div class='card-sub'>Temp: <span id='v-ph-t'>--</span> °C</div>"
    "</div>"

    /* ORP */
    "<div class='card'>"
      "<div class='card-title'>⚡ ORP</div>"
      "<div><span class='card-val' id='v-orp'>--</span><span class='card-unit'>mV</span></div>"
      "<div class='card-sub'>Temp: <span id='v-orp-t'>--</span> °C</div>"
    "</div>"

    /* EC */
    "<div class='card'>"
      "<div class='card-title'>🌊 Conductivity (EC)</div>"
      "<div><span class='card-val' id='v-ec'>--</span><span class='card-unit'>mS/cm</span></div>"
      "<div class='card-sub'>Temp: <span id='v-ec-t'>--</span> °C</div>"
    "</div>"

    /* DO */
    "<div class='card'>"
      "<div class='card-title'>💧 Dissolved O₂</div>"
      "<div><span class='card-val' id='v-do'>--</span><span class='card-unit'>mg/L</span></div>"
      "<div class='card-sub'>Temp: <span id='v-do-t'>--</span> °C</div>"
    "</div>"

    /* Ammonia */
    "<div class='card'>"
      "<div class='card-title'>🧪 Ammonia</div>"
      "<div><span class='card-val' id='v-nh3'>--</span><span class='card-unit'>mg/L</span></div>"
      "<div class='card-sub'>Temp: <span id='v-nh3-t'>--</span> °C</div>"
    "</div>"

    /* Single Ultrasonic */
    "<div class='card'>"
      "<div class='card-title'>🔊 Ultrasonic Distance</div>"
      "<div><span class='card-val' id='v-ultra'>--</span><span class='card-unit'>mm</span></div>"
      "<div class='card-sub'>Temp: <span id='v-ultra-t'>--</span> °C</div>"
    "</div>"

    /* Multi-Ultrasonic Board */
    "<div class='card' style='grid-column:span 2'>"
      "<div class='card-title'>🔊 Multi-US Board</div>"
      "<div class='multi-us-grid'>"
        "<div>US1: <span id='v-us1'>--</span>mm</div>"
        "<div>US2: <span id='v-us2'>--</span>mm</div>"
        "<div>US3: <span id='v-us3'>--</span>mm</div>"
        "<div>US4: <span id='v-us4'>--</span>mm</div>"
        "<div>US5: <span id='v-us5'>--</span>mm</div>"
        "<div>US6: <span id='v-us6'>--</span>mm</div>"
        "<div>US7: <span id='v-us7'>--</span>mm</div>"
        "<div>US8: <span id='v-us8'>--</span>mm</div>"
      "</div>"
      "<div class='card-sub'>Avg: <span id='v-us-avg'>--</span>mm &nbsp; Comp: <span id='v-us-comp'>--</span>mm &nbsp; Temp: <span id='v-us-temp'>--</span>°C</div>"
    "</div>"

    /* QR */
    "<div class='card' style='grid-column:span 1'>"
      "<div class='card-title'>📱 Board Identity QR</div>"
      "<div id='qr-container'><canvas id='qr-canvas' width='140' height='140'></canvas></div>"
      "<div id='qr-label' style='text-align:center;font-size:.68rem;color:var(--muted);margin-top:6px'></div>"
    "</div>"
  "</div>"

  /* Relay Status Row */
  "<div class='form-section'>"
    "<h3>⚡ Relay Status</h3>"
    "<div class='relay-grid' id='relay-status-grid'>"
      "<!-- populated by JS -->"
    "</div>"
  "</div>"
"</div>"

/* ============ PAGE: CONFIGS ============ */
"<div class='page' id='page-configs'>"
  "<div class='form-section'>"
    "<h3>Relay Pin Mapping &amp; Mode Configuration</h3>"
    "<div id='relay-config-grid'>"
      "<!-- populated by JS -->"
    "</div>"
    "<div style='margin-top:16px;display:flex;gap:10px'>"
      "<button class='btn btn-danger btn-sm' onclick='allRelaysOff()'>🔴 All OFF</button>"
      "<button class='btn btn-success btn-sm' onclick='allRelaysOn()'>🟢 All ON</button>"
    "</div>"
    "<div id='relay-save-msg'></div>"
  "</div>"

  "<div class='form-section' style='margin-top:20px'>"
    "<h3>⚙️ Sensors Modbus ID Configuration</h3>"
    "<div class='grid grid2' style='gap:12px;margin-bottom:16px'>"
      "<div><label>pH Sensor ID</label><input id='scf-ph' type='number' min='1' max='247' value='1'/></div>"
      "<div><label>ORP Sensor ID</label><input id='scf-orp' type='number' min='1' max='247' value='2'/></div>"
      "<div><label>EC Sensor ID</label><input id='scf-ec' type='number' min='1' max='247' value='3'/></div>"
      "<div><label>DO Sensor ID</label><input id='scf-do' type='number' min='1' max='247' value='4'/></div>"
      "<div><label>Ammonia ID</label><input id='scf-nh3' type='number' min='1' max='247' value='5'/></div>"
      "<div><label>Ultrasonic ID</label><input id='scf-ultra' type='number' min='1' max='247' value='10'/></div>"
      "<div><label>Multi-US ID</label><input id='scf-multi-us' type='number' min='1' max='247' value='10'/></div>"
      "<div><label>Single US ID</label><input id='scf-single-us' type='number' min='0' max='247' value='0'/></div>"
    "</div>"
    "<button class='btn btn-primary btn-sm' onclick='saveSensors()'>💾 Save Sensor IDs</button>"
    "<div id='sensors-save-msg' style='margin-top:8px'></div>"
  "</div>"

  "<div class='form-section' style='margin-top:20px'>"
    "<h3>🔍 Modbus Network Scanner</h3>"
    "<p style='font-size:.78rem;color:var(--muted);margin-bottom:14px'>"
      "Scans Modbus IDs 1 to 247 on the RS485 bus to automatically detect connected sensors."
    "</p>"
    "<div style='display:flex;align-items:center;gap:12px;margin-bottom:16px'>"
      "<button class='btn btn-primary btn-sm' id='scan-btn' onclick='startModbusScan()'>🔍 Scan Network</button>"
      "<div id='scan-progress-container' style='flex-grow:1;display:none;background:var(--border);height:10px;border-radius:5px;overflow:hidden;min-width:150px'>"
        "<div id='scan-progress-bar' style='background:var(--green);width:0%;height:100%;transition:width 0.1s'></div>"
      "</div>"
      "<span id='scan-status-lbl' style='font-size:.85rem;font-weight:600'></span>"
    "</div>"
    "<div id='scan-results-container' style='display:none'>"
      "<h4>Discovered Devices</h4>"
      "<div style='overflow-x:auto'>"
        "<table style='width:100%;border-collapse:collapse;margin-top:8px'>"
          "<thead>"
            "<tr style='border-bottom:2px solid var(--border);text-align:left;font-size:.85rem'>"
              "<th style='padding:8px'>Modbus ID</th>"
              "<th style='padding:8px'>Device Type</th>"
            "</tr>"
          "</thead>"
          "<tbody id='scan-results-body'>"
          "</tbody>"
        "</table>"
      "</div>"
    "</div>"
  "</div>"
"</div>"

/* ============ PAGE: MQTT ============ */
"<div class='page' id='page-mqtt'>"
  "<div class='form-section'>"
    "<h3>Cloud MQTT Provisioning</h3>"
    "<div class='form-row'>"
      "<div><label>Broker Host / IP</label><input id='mqtt-broker' placeholder='mqtt.example.com'/></div>"
      "<div><label>Port</label><input id='mqtt-port' type='number' value='1883'/></div>"
    "</div>"
    "<div class='form-row'>"
      "<div><label>Client ID</label><input id='mqtt-client' placeholder='kontrx-gateway-01'/></div>"
      "<div><label>Username</label><input id='mqtt-user' placeholder='(optional)'/></div>"
      "<div><label>Password</label><input id='mqtt-pass' type='password' placeholder='(optional)'/></div>"
    "</div>"
    "<button class='btn btn-primary' onclick='saveMQTT()'>☁️ Save &amp; Connect</button>"
    "<div id='mqtt-msg'></div>"
  "</div>"
"</div>"

/* ============ PAGE: OTA ============ */
"<div class='page' id='page-ota'>"
  "<div class='form-section' id='ota-upload-panel'>"
    "<h3>📦 Firmware Upload</h3>"
    "<p style='font-size:.78rem;color:var(--muted);margin-bottom:14px'>"
      "Select the Kontrx.bin firmware file. The device will write it to the staging flash area,"
      "verify CRC, and reboot into the bootloader for automatic swap."
    "</p>"
    "<div style='background:rgba(5,10,20,.6);border:2px dashed var(--border);border-radius:12px;"
      "padding:30px;text-align:center;margin-bottom:16px' id='drop-zone'"
      "ondragover='event.preventDefault()' ondrop='handleDrop(event)'>"
      "<div style='font-size:2rem;margin-bottom:8px'>📁</div>"
      "<div style='font-size:.85rem;color:var(--muted)'>Drag &amp; Drop Kontrx.bin here, or</div>"
      "<label class='btn btn-primary' style='margin-top:10px;display:inline-flex;cursor:pointer'>"
        "🗂 Choose File<input type='file' id='fw-file' accept='.bin' style='display:none' onchange='fileSelected()'>"
      "</label>"
      "<div id='fw-name' style='font-size:.75rem;color:var(--accent);margin-top:8px'></div>"
    "</div>"
    "<div class='progress-wrap'><div class='progress-bar' id='ota-bar'></div></div>"
    "<div id='ota-pct' style='font-size:.75rem;color:var(--muted);text-align:center;margin-bottom:12px'>Awaiting file...</div>"
    "<button class='btn btn-success' id='btn-flash' onclick='uploadFirmware()' disabled>⚡ Flash Firmware</button>"
    "<div id='ota-msg'></div>"
  "</div>"
"</div>"

"</div>"
/* ============ SCRIPTS ============ */
"<script>"

/* ----- State ----- */
"var otpUnlocked=true;"
"var relayNames=['PE2','PE4','PE6','PC0','PC2','PA0','PA2','PA4','PC4','PD8'];"
"var relayNC=[0,0,0,0,0,0,0,0,0,0];"
"var relayState=[0,0,0,0,0,0,0,0,0,0];"
"var portOpts=['A','B','C','D','E'];"
"var statusTimer=null;"
"var uptimeTimer=null;"

/* ----- Tab Navigation ----- */
"function showTab(t){"
  "document.querySelectorAll('.page').forEach(p=>p.classList.remove('active'));"
  "document.querySelectorAll('.tab').forEach(b=>b.classList.remove('active'));"
  "document.getElementById('page-'+t).classList.add('active');"
  "event.currentTarget.classList.add('active');"
"}"

/* ----- Relay status grid ----- */
"function buildRelayStatusGrid(){"
  "var g=document.getElementById('relay-status-grid');g.innerHTML='';"
  "for(var i=0;i<10;i++){"
    "var d=document.createElement('div');"
    "d.className='relay-btn '+(relayState[i]?'on':'off');"
    "d.id='rsb-'+i;"
    "d.innerHTML='<div class=\"relay-led\"></div>'+"
      "'<div class=\"relay-name\">R'+(i+1)+'</div>'+"
      "'<div class=\"relay-pin\">'+relayNames[i]+'</div>'+"
      "'<div class=\"relay-nc\">'+(relayNC[i]?'NC':'NO')+'</div>';"
    "d.onclick=(function(idx){return function(){toggleRelay(idx);};})(i);"
    "g.appendChild(d);"
  "}"
"}"/* ----- Relay config grid ----- */
"var configLoadedFromServer=false;"
"var configGridBuilt=false;"
"function updateRelayConfigStates(){"
  "for(var i=0;i<10;i++){"
    "var btn=document.getElementById('rtgl-btn-'+i);"
    "var txt=document.getElementById('rtgl-'+i);"
    "if(btn&&txt){"
      "btn.className='btn btn-sm '+(relayState[i]?'btn-success':'btn-danger');"
      "txt.textContent=relayState[i]?'ON':'OFF';"
    "}"
  "}"
"}"
"function buildRelayConfigGrid(){"
  "var g=document.getElementById('relay-config-grid');if(!g)return;"
  "if(configGridBuilt && configLoadedFromServer){updateRelayConfigStates();return;}"
  "g.innerHTML='';"
  "for(var i=0;i<10;i++){"
    "var row=document.createElement('div');"
    "row.style='display:grid;grid-template-columns:40px 110px 180px 80px 140px;gap:10px;align-items:center;padding:10px 0;border-bottom:1px solid rgba(30,58,95,.4)';"
    "row.innerHTML="
      "'<div style=\"font-size:.8rem;font-weight:700;color:var(--accent)\">R'+(i+1)+'</div>'+"
      "'<div><label>Pin</label><input id=\"rcf-pin-'+i+'\" style=\"padding:8px 10px;text-transform:uppercase;font-weight:700\" value=\"'+relayNames[i]+'\" onchange=\"autoSaveRelayConfig('+i+')\" onkeydown=\"if(event.key===\\'Enter\\')this.blur()\"/></div>'+"
      "'<div><label>Mode</label><select id=\"rcf-nc-'+i+'\" style=\"padding:8px 10px;min-width:170px;font-weight:600\" onchange=\"autoSaveRelayConfig('+i+')\">'+"
        "'<option value=\"0\"'+(relayNC[i]==0?' selected':'')+'>NO (Normal Open)</option>'+"
        "'<option value=\"1\"'+(relayNC[i]==1?' selected':'')+'>NC (Normal Closed)</option>'+"
      "'</select></div>'+"
      "'<div><label>Current</label>'+"
        "'<button id=\"rtgl-btn-'+i+'\" class=\"btn btn-sm '+(relayState[i]?'btn-success':'btn-danger')+'\" onclick=\"toggleRelay('+i+')\">'+"
          "'<span id=\"rtgl-'+i+'\">'+(relayState[i]?'ON':'OFF')+'</span></button>'+"
      "'</div>'+"
      "'<div><label>Status</label>'+"
        "'<div id=\"rcf-status-'+i+'\" style=\"display:flex;align-items:center;height:32px;font-size:.7rem;color:var(--muted)\">✓ Saved</div>'+"
      "'</div>';"
    "g.appendChild(row);"
  "}"
  "if(configLoadedFromServer){"
    "configGridBuilt=true;"
  "}"
"}"

"function autoSaveRelayConfig(i){"
  "var pinEl=document.getElementById('rcf-pin-'+i);"
  "var ncEl=document.getElementById('rcf-nc-'+i);"
  "var statusEl=document.getElementById('rcf-status-'+i);"
  "if(!pinEl||!ncEl||!statusEl)return;"
  "var pin=pinEl.value.trim().toUpperCase();"
  "var nc=parseInt(ncEl.value);"
  "var match=pin.match(/^P?([A-E])([0-9]{1,2})$/);"
  "if(!match){"
    "statusEl.innerHTML='<span style=\"color:var(--red)\">⚠️ Invalid pin</span>';"
    "pinEl.style.borderColor='var(--red)';"
    "return;"
  "}"
  "var port=match[1];var pinNum=parseInt(match[2]);"
  "if(pinNum<0||pinNum>15){"
    "statusEl.innerHTML='<span style=\"color:var(--red)\">⚠️ Pin 0..15</span>';"
    "pinEl.style.borderColor='var(--red)';"
    "return;"
  "}"
  "var formatted='P'+port+pinNum;"
  "if(RESERVED_PINS[formatted]){"
    "statusEl.innerHTML='<span style=\"color:var(--red)\">⚠️ Reserved</span>';"
    "pinEl.style.borderColor='var(--red)';"
    "return;"
  "}"
  "for(var j=0;j<10;j++){"
    "if(j===i)continue;"
    "var otherPinEl=document.getElementById('rcf-pin-'+j);"
    "var otherPin=otherPinEl?otherPinEl.value.trim().toUpperCase():relayNames[j];"
    "var oMatch=otherPin.match(/^P?([A-E])([0-9]{1,2})$/);"
    "if(oMatch && 'P'+oMatch[1]+parseInt(oMatch[2])===formatted){"
      "statusEl.innerHTML='<span style=\"color:var(--red)\">⚠️ Duplicate</span>';"
      "pinEl.style.borderColor='var(--red)';"
      "return;"
    "}"
  "}"
  "statusEl.innerHTML='<span style=\"color:var(--orange)\">⏳ Saving...</span>';"
  "pinEl.style.borderColor='var(--border)';"
  "var payload=[{id:i,pin:pin,nc:nc}];"
  "fetch('/api/config/relays',{method:'POST',"
    "headers:{'Content-Type':'application/json'},"
    "body:JSON.stringify({relays:payload})})"
  ".then(r=>r.json()).then(d=>{"
    "if(d.ok){"
      "statusEl.innerHTML='<span style=\"color:var(--green)\">✓ Saved</span>';"
      "relayNames[i]=pin;relayNC[i]=nc;"
      "buildRelayStatusGrid();"
      "setTimeout(function(){"
        "if(statusEl.textContent==='✓ Saved'){"
          "statusEl.innerHTML='<span style=\"color:var(--muted)\">✓ Saved</span>';"
        "}"
      "},2000);"
    "}"
  "}).catch(function(){"
    "statusEl.innerHTML='<span style=\"color:var(--red)\">⚠️ Error</span>';"
  "});"
"}"

"function toggleRelay(i){"
  "fetch('/api/relay?id='+i+'&state='+(relayState[i]?0:1),{method:'POST'})"
  ".then(r=>r.json()).then(d=>{"
    "relayState[i]=d.state;"
    "buildRelayStatusGrid();"
    "updateRelayConfigStates();"
  "}).catch(()=>{});"
"}"

"function allRelaysOff(){"
  "fetch('/api/relay/all?state=0',{method:'POST'}).then(()=>fetchStatus());"
"}"
"function allRelaysOn(){"
  "fetch('/api/relay/all?state=1',{method:'POST'}).then(()=>fetchStatus());"
"}"

"var RESERVED_PINS={"
  "'PA6':'LED Indicator',"
  "'PA9':'USART1 Debug Console (TX)',"
  "'PA10':'USART1 Debug Console (RX)',"
  "'PB10':'USART3 Modbus RTU (TX)',"
  "'PB11':'USART3 Modbus RTU (RX)',"
  "'PB12':'SPI2 W5500 Ethernet (CS)',"
  "'PB13':'SPI2 W5500 Ethernet (SCK)',"
  "'PB14':'SPI2 W5500 Ethernet (MISO)',"
  "'PB15':'SPI2 W5500 Ethernet (MOSI)',"
  "'PD2':'MAX485 Driver (RE Control)',"
  "'PD3':'MAX485 Driver (DE Control)'"
"};"

"function validatePins(){"
  "var used={};"
  "for(var i=0;i<10;i++){"
    "var el=document.getElementById('rcf-pin-'+i);if(!el)continue;"
    "var raw=el.value.trim().toUpperCase();"
    "var match=raw.match(/^P?([A-E])([0-9]{1,2})$/);"
    "if(!match)return {ok:false,msg:'R'+(i+1)+' has invalid pin format (e.g. PE2, PC12, A0)'};"
    "var port=match[1];var pin=parseInt(match[2]);"
    "if(pin<0||pin>15)return {ok:false,msg:'R'+(i+1)+' pin number must be 0 to 15'};"
    "var formatted='P'+port+pin;"
    "if(RESERVED_PINS[formatted])return {ok:false,msg:'Pin '+formatted+' is reserved for '+RESERVED_PINS[formatted]};"
    "if(used[formatted]!=null)return {ok:false,msg:'Pin '+formatted+' is assigned to both R'+(used[formatted]+1)+' and R'+(i+1)};"
    "used[formatted]=i;"
  "}"
  "return {ok:true};"
"}"

"function saveMQTT(){"
  "var payload={"
    "broker:document.getElementById('mqtt-broker').value,"
    "port:parseInt(document.getElementById('mqtt-port').value)||1883,"
    "client_id:document.getElementById('mqtt-client').value,"
    "username:document.getElementById('mqtt-user').value,"
    "password:document.getElementById('mqtt-pass').value"
  "};"
  "fetch('/api/config/mqtt',{method:'POST',"
    "headers:{'Content-Type':'application/json'},"
    "body:JSON.stringify(payload)})"
  ".then(r=>r.json())"
  ".then(d=>showMsg('mqtt-msg','MQTT config saved!','ok'))"
  ".catch(()=>showMsg('mqtt-msg','Save failed.','err'));"
"}"

"function saveSensors(){"
  "var payload={"
    "ph:parseInt(document.getElementById('scf-ph').value),"
    "orp:parseInt(document.getElementById('scf-orp').value),"
    "ec:parseInt(document.getElementById('scf-ec').value),"
    "do:parseInt(document.getElementById('scf-do').value),"
    "ammonia:parseInt(document.getElementById('scf-nh3').value),"
    "multi_us:parseInt(document.getElementById('scf-multi-us').value),"
    "single_us:parseInt(document.getElementById('scf-single-us').value)"
  "};"
  "fetch('/api/config/sensors',{method:'POST',"
    "headers:{'Content-Type':'application/json'},"
    "body:JSON.stringify(payload)})"
  ".then(r=>r.json())"
  ".then(d=>{"
    "var el=document.getElementById('sensors-save-msg');"
    "el.innerHTML='<span style=\"color:var(--green)\">✓ Config saved</span>';"
    "setTimeout(()=>el.innerHTML='',2000);"
  "})"
  ".catch(()=>{});"
"}"

"var scanTimer=null;"
"function startModbusScan(){"
  "var btn=document.getElementById('scan-btn');"
  "btn.disabled=true;"
  "document.getElementById('scan-progress-container').style.display='block';"
  "document.getElementById('scan-results-container').style.display='none';"
  "document.getElementById('scan-status-lbl').textContent='Starting scan...';"
  "document.getElementById('scan-progress-bar').style.width='0%';"
  
  "fetch('/api/modbus/scan',{method:'POST'})"
  ".then(()=>{"
    "scanTimer=setInterval(pollScanStatus,500);"
  "});"
"}"

"function pollScanStatus(){"
  "fetch('/api/modbus/scan')"
  ".then(r=>r.json())"
  ".then(d=>{"
    "document.getElementById('scan-progress-bar').style.width=d.progress+'%';"
    "document.getElementById('scan-status-lbl').textContent=d.progress+'%';"
    "if(d.scanning===false){"
      "clearInterval(scanTimer);"
      "document.getElementById('scan-btn').disabled=false;"
      "document.getElementById('scan-status-lbl').textContent='Scan complete!';"
      "displayScanResults(d.devices);"
    "}"
  "}).catch(()=>{"
    "clearInterval(scanTimer);"
    "document.getElementById('scan-btn').disabled=false;"
  "});"
"}"

"function displayScanResults(devs){"
  "var body=document.getElementById('scan-results-body');"
  "body.innerHTML='';"
  "document.getElementById('scan-results-container').style.display='block';"
  "if(devs.length===0){"
    "body.innerHTML='<tr><td colspan=\"2\" style=\"padding:8px;text-align:center;color:var(--muted)\">No devices found.</td></tr>';"
    "return;"
  "}"
  "var types=['?','pH Sensor','ORP Sensor','Conductivity (EC)','Dissolved O₂ (DO)','Ammonia Sensor','Ultrasonic Sensor'];"
  "devs.forEach(dev=>{"
    "var tr=document.createElement('tr');"
    "tr.style.borderBottom='1px solid var(--border)';"
    "var name=types[dev.type]||'Unknown Device';"
    "tr.innerHTML='<td style=\"padding:8px;font-weight:600\">'+dev.id+'</td><td style=\"padding:8px\">'+name+'</td>';"
    "body.appendChild(tr);"
  "});"
"}"

"function fetchStatus(){"
  "var ctrl=new AbortController();"
  "var tid=setTimeout(function(){ctrl.abort();},3000);"
  "fetch('/api/status',{signal:ctrl.signal})"
  ".then(function(r){clearTimeout(tid);return r.json();})"
  ".then(function(d){"
"var fmtF=function(v){return(v==null||v<=-900)?'---':v.toFixed(2);};"
    "var fmtI=function(v){return(v==null||v<=-900)?'---':Math.round(v);};"
    "document.getElementById('v-ph').textContent=fmtF(d.ph);"
    "document.getElementById('v-ph-t').textContent=fmtF(d.ph_temp);"
    "document.getElementById('v-orp').textContent=fmtF(d.orp);"
    "document.getElementById('v-orp-t').textContent=fmtF(d.orp_temp);"
    "document.getElementById('v-ec').textContent=fmtF(d.ec);"
    "document.getElementById('v-ec-t').textContent=fmtF(d.ec_temp);"
    "document.getElementById('v-do').textContent=fmtF(d.do_val);"
    "document.getElementById('v-do-t').textContent=fmtF(d.do_temp);"
    "document.getElementById('v-nh3').textContent=fmtF(d.ammonia);"
    "document.getElementById('v-nh3-t').textContent=fmtF(d.ammonia_temp);"
    "document.getElementById('v-ultra').textContent=fmtF(d.ultra_dist);"
    "document.getElementById('v-ultra-t').textContent=fmtF(d.ultra_temp);"
    "for(var _i=1;_i<=8;_i++){"
      "var _el=document.getElementById('v-us'+_i);"
      "if(_el)_el.textContent=fmtI(d['us'+_i]);"
    "}"
    "if(d.us_avg!=null)document.getElementById('v-us-avg').textContent=fmtI(d.us_avg);"
    "if(d.us_comp!=null)document.getElementById('v-us-comp').textContent=fmtI(d.us_comp);"
    "if(d.us_temp!=null)document.getElementById('v-us-temp').textContent=fmtF(d.us_temp);"
    "if(d.sensor_ids){"
      "var inputs=['scf-ph','scf-orp','scf-ec','scf-do','scf-nh3','scf-multi-us','scf-single-us'];"
      "inputs.forEach(function(id, idx){"
        "var el=document.getElementById(id);"
        "if(el && document.activeElement !== el) el.value = d.sensor_ids[idx];"
      "});"
    "}"
    "if(d.relays){"
      "configLoadedFromServer=true;"
      "d.relays.forEach(function(r,i){"
        "relayState[i]=r.state;"
        "if(r.nc!=null)relayNC[i]=r.nc;"
        "if(r.pin)relayNames[i]=r.pin;"
      "});"
      "buildRelayStatusGrid();"
      "buildRelayConfigGrid();"
    "}"
    "if(typeof d.uptime_s==='number'){"
      "var us=d.uptime_s;"
      "var hu=Math.floor(us/3600);"
      "var mu=Math.floor((us%3600)/60);"
      "var su=us%60;"
      "document.getElementById('uptime-val').textContent="
        "(hu<10?'0':'')+hu+':'+(mu<10?'0':'')+mu+':'+(su<10?'0':'')+su;"
    "}"
    "document.getElementById('conn-dot').style.background='var(--green)';"
    "document.getElementById('conn-lbl').textContent='Online';"
    "generateQR(d);"
  "})"
  ".catch(function(){"
    "clearTimeout(tid);"
    "document.getElementById('conn-dot').style.background='var(--red)';"
    "document.getElementById('conn-lbl').textContent='Offline';"
  "});"
"}"

"function startPolling(){"
  "setTimeout(function(){"
    "fetchStatus();"
    "statusTimer=setInterval(fetchStatus,1500);"
  "},2500);"
"}"

"var qrcode=(function(){"
  "var PAD0=0xEC,PAD1=0x11;"
  "function QRCode(t,e){this.typeNumber=t;this.errorCorrectionLevel=e;this.modules=null;this.moduleCount=0;this.dataList=[];}"
  "QRCode.prototype={"
    "addData:function(d){this.dataList.push({mode:4,data:d,getLength:function(){return this.data.length;},write:function(b){for(var i=0;i<this.data.length;i++)b.put(this.data.charCodeAt(i),8);}});},"
    "isDark:function(r,c){return this.modules[r][c];},"
    "getModuleCount:function(){return this.moduleCount;},"
    "make:function(){"
      "var t=1;"
      "for(t=1;t<10;t++){"































        "var b=QRRSBlock.getRSBlocks(t,this.errorCorrectionLevel),buf=new QRBitBuffer(),tot=0;"
        "for(var i=0;i<b.length;i++)tot+=b[i].dataCount;"
        "for(var i=0;i<this.dataList.length;i++){var d=this.dataList[i];buf.put(d.mode,4);buf.put(d.getLength(),8);d.write(buf);}"
        "if(buf.getLengthInBits()<=tot*8)break;"
      "}"
      "this.typeNumber=t;this.makeImpl(false,this.getBestMaskPattern());"
    "},"
    "makeImpl:function(test,mask){"
      "this.moduleCount=this.typeNumber*4+17;"
      "this.modules=new Array(this.moduleCount);"
      "for(var r=0;r<this.moduleCount;r++){this.modules[r]=new Array(this.moduleCount);for(var c=0;c<this.moduleCount;c++)this.modules[r][c]=null;}"
      "this.setupPositionProbePattern(0,0);this.setupPositionProbePattern(this.moduleCount-7,0);this.setupPositionProbePattern(0,this.moduleCount-7);"
      "this.setupPositionAdjustPattern();this.setupTimingPattern();this.setupTypeInfo(test,mask);"
      "var data=QRCode.createData(this.typeNumber,this.errorCorrectionLevel,this.dataList);"
      "this.mapData(data,mask);"
    "},"
    "setupPositionProbePattern:function(row,col){"
      "for(var r=-1;r<=7;r++){"
        "if(row+r<=-1||this.moduleCount<=row+r)continue;"
        "for(var c=-1;c<=7;c++){"
          "if(col+c<=-1||this.moduleCount<=col+c)continue;"
          "this.modules[row+r][col+c]=(0<=r&&r<=6&&(c==0||c==6))||(0<=c&&c<=6&&(r==0||r==6))||(2<=r&&r<=4&&2<=c&&c<=4);"
        "}"
      "}"
    "},"
    "getBestMaskPattern:function(){"
      "var min=0,best=0;"
      "for(var i=0;i<8;i++){this.makeImpl(true,i);var p=QRUtil.getLostPoint(this);if(i==0||min>p){min=p;best=i;}}"
      "return best;"
    "},"
    "setupTimingPattern:function(){"
      "for(var r=8;r<this.moduleCount-8;r++){if(this.modules[r][6]!=null)continue;this.modules[r][6]=(r%2==0);}"
      "for(var c=8;c<this.moduleCount-8;c++){if(this.modules[6][c]!=null)continue;this.modules[6][c]=(c%2==0);}"
    "},"
    "setupPositionAdjustPattern:function(){"
      "var pos=QRUtil.getPatternPosition(this.typeNumber);"
      "for(var i=0;i<pos.length;i++)for(var j=0;j<pos.length;j++){"
        "var row=pos[i],col=pos[j];if(this.modules[row][col]!=null)continue;"
        "for(var r=-2;r<=2;r++)for(var c=-2;c<=2;c++)this.modules[row+r][col+c]=(r==-2||r==2||c==-2||c==2||(r==0&&c==0));"
      "}"
    "},"
    "setupTypeInfo:function(test,mask){"
      "var bits=QRUtil.getBCHTypeInfo((this.errorCorrectionLevel<<3)|mask);"
      "for(var i=0;i<15;i++){"
        "var mod=(!test&&((bits>>i)&1)==1);"
        "if(i<6)this.modules[i][8]=mod;else if(i<8)this.modules[i+1][8]=mod;else this.modules[this.moduleCount-15+i][8]=mod;"
        "if(i<8)this.modules[8][this.moduleCount-i-1]=mod;else if(i<9)this.modules[8][15-i-1+1]=mod;else this.modules[8][15-i-1]=mod;"
      "}"
      "this.modules[this.moduleCount-8][8]=(!test);"
    "},"
    "mapData:function(data,mask){"
      "var inc=-1,row=this.moduleCount-1,bitIndex=7,byteIndex=0;"
      "for(var col=this.moduleCount-1;col>0;col-=2){"
        "if(col==6)col--;"
        "while(true){"
          "for(var c=0;c<2;c++){"
            "if(this.modules[row][col-c]==null){"
              "var dark=(byteIndex<data.length)?(((data[byteIndex]>>>bitIndex)&1)==1):false;"
              "if(QRUtil.getMask(mask,row,col-c))dark=!dark;"
              "this.modules[row][col-c]=dark;bitIndex--;"
              "if(bitIndex==-1){byteIndex++;bitIndex=7;}"
            "}"
          "}"
          "row+=inc;if(row<0||this.moduleCount<=row){row-=inc;inc=-inc;break;}"
        "}"
      "}"
    "}"
  "};"
  "QRCode.createData=function(typeNumber,errorCorrectionLevel,dataList){"
    "var rsBlocks=QRRSBlock.getRSBlocks(typeNumber,errorCorrectionLevel),buffer=new QRBitBuffer();"
    "for(var i=0;i<dataList.length;i++){var d=dataList[i];buffer.put(d.mode,4);buffer.put(d.getLength(),8);d.write(buffer);}"
    "var totalDataCount=0;for(var i=0;i<rsBlocks.length;i++)totalDataCount+=rsBlocks[i].dataCount;"
    "if(buffer.getLengthInBits()+4<=totalDataCount*8)buffer.put(0,4);"
    "while(buffer.getLengthInBits()%8!=0)buffer.putBit(false);"
    "while(true){if(buffer.getLengthInBits()>=totalDataCount*8)break;buffer.put(PAD0,8);if(buffer.getLengthInBits()>=totalDataCount*8)break;buffer.put(PAD1,8);}"
    "return QRCode.createBytes(buffer,rsBlocks);"
  "};"
  "QRCode.createBytes=function(buffer,rsBlocks){"
    "var offset=0,maxDc=0,maxEc=0,dcdata=new Array(rsBlocks.length),ecdata=new Array(rsBlocks.length);"
    "for(var r=0;r<rsBlocks.length;r++){"
      "var dcCount=rsBlocks[r].dataCount,ecCount=rsBlocks[r].totalCount-dcCount;"
      "maxDc=Math.max(maxDc,dcCount);maxEc=Math.max(maxEc,ecCount);"
      "dcdata[r]=new Array(dcCount);for(var i=0;i<dcdata[r].length;i++)dcdata[r][i]=0xff&buffer.buffer[i+offset];"
      "offset+=dcCount;"
      "var rsPoly=QRUtil.getErrorCorrectPolynomial(ecCount),rawPoly=new QRPolynomial(dcdata[r],rsPoly.getLength()-1);"
      "var modPoly=rawPoly.mod(rsPoly);ecdata[r]=new Array(rsPoly.getLength()-1);"
      "for(var i=0;i<ecdata[r].length;i++){var idx=i+modPoly.getLength()-ecdata[r].length;ecdata[r][i]=(idx>=0)?modPoly.get(idx):0;}"
    "}"
    "var totalCodeCount=0;for(var i=0;i<rsBlocks.length;i++)totalCodeCount+=rsBlocks[i].totalCount;"
    "var data=new Array(totalCodeCount),index=0;"
    "for(var i=0;i<maxDc;i++)for(var r=0;r<rsBlocks.length;r++)if(i<dcdata[r].length)data[index++]=dcdata[r][i];"
    "for(var i=0;i<maxEc;i++)for(var r=0;r<rsBlocks.length;r++)if(i<ecdata[r].length)data[index++]=ecdata[r][i];"
    "return data;"
  "};"
  "var QRUtil={"
    "PATTERN_POSITION_TABLE:[[],[6,18],[6,22],[6,26],[6,30],[6,34],[6,22,38],[6,24,42],[6,26,46],[6,28,50]],"
    "G15:(1<<10)|(1<<8)|(1<<5)|(1<<4)|(1<<2)|(1<<1)|(1<<0),G15_MASK:(1<<14)|(1<<12)|(1<<8)|(1<<4)|(1<<1),"
    "getBCHTypeInfo:function(data){var d=data<<10;while(QRUtil.getBCHDigit(d)-QRUtil.getBCHDigit(QRUtil.G15)>=0)d^=(QRUtil.G15<<(QRUtil.getBCHDigit(d)-QRUtil.getBCHDigit(QRUtil.G15)));return((data<<10)|d)^QRUtil.G15_MASK;},"
    "getBCHDigit:function(data){var digit=0;while(data!=0){digit++;data>>>=1;}return digit;},"
    "getPatternPosition:function(t){return QRUtil.PATTERN_POSITION_TABLE[t-1];},"
    "getMask:function(m,i,j){"
      "switch(m){"
        "case 0:return(i+j)%2==0;case 1:return i%2==0;case 2:return j%3==0;case 3:return(i+j)%3==0;"
        "case 4:return(Math.floor(i/2)+Math.floor(j/3))%2==0;case 5:return(i*j)%2+(i*j)%3==0;"
        "case 6:return((i*j)%2+(i*j)%3)%2==0;case 7:return((i*j)%3+(i+j)%2)%2==0;"
        "default:return false;"
      "}"
    "},"
    "getErrorCorrectPolynomial:function(len){var a=new QRPolynomial([1],0);for(var i=0;i<len;i++)a=a.multiply(new QRPolynomial([1,QRMath.gexp(i)],0));return a;},"
    "getLostPoint:function(qr){"
      "var mc=qr.getModuleCount(),lp=0;"
      "for(var r=0;r<mc;r++)for(var c=0;c<mc;c++){"
        "var same=0,dark=qr.isDark(r,c);"
        "for(var dr=-1;dr<=1;dr++){if(r+dr<0||mc<=r+dr)continue;for(var dc=-1;dc<=1;dc++){if(c+dc<0||mc<=c+dc)continue;if(dr==0&&dc==0)continue;if(dark==qr.isDark(r+dr,c+dc))same++;}}"
        "if(same>5)lp+=(3+same-5);"
      "}"
      "return lp;"
    "}"
  "};"
  "var QRMath={"
    "glog:function(n){return QRMath.LOG_TABLE[n];},"
    "gexp:function(n){while(n<0)n+=255;while(n>=255)n-=255;return QRMath.EXP_TABLE[n];},"
    "EXP_TABLE:new Array(256),LOG_TABLE:new Array(256)"
  "};"
  "for(var i=0;i<8;i++)QRMath.EXP_TABLE[i]=1<<i;"
  "for(var i=8;i<256;i++)QRMath.EXP_TABLE[i]=QRMath.EXP_TABLE[i-4]^QRMath.EXP_TABLE[i-5]^QRMath.EXP_TABLE[i-6]^QRMath.EXP_TABLE[i-8];"
  "for(var i=0;i<255;i++)QRMath.LOG_TABLE[QRMath.EXP_TABLE[i]]=i;"
  "function QRPolynomial(num,shift){"
    "var offset=0;while(offset<num.length&&num[offset]==0)offset++;"
    "this.num=new Array(num.length-offset+shift);for(var i=0;i<num.length-offset;i++)this.num[i]=num[i+offset];"
  "}"
  "QRPolynomial.prototype={"
    "get:function(i){return this.num[i];},getLength:function(){return this.num.length;},"
    "multiply:function(e){"
      "var num=new Array(this.getLength()+e.getLength()-1);"
      "for(var i=0;i<this.getLength();i++)for(var j=0;j<e.getLength();j++)num[i+j]^=QRMath.gexp(QRMath.glog(this.get(i))+QRMath.glog(e.get(j)));"
      "return new QRPolynomial(num,0);"
    "},"
    "mod:function(e){"
      "if(this.getLength()-e.getLength()<0)return this;"
      "var ratio=QRMath.glog(this.get(0))-QRMath.glog(e.get(0)),num=new Array(this.getLength());"
      "for(var i=0;i<this.getLength();i++)num[i]=this.get(i);"
      "for(var i=0;i<e.getLength();i++)num[i]^=QRMath.gexp(QRMath.glog(e.get(i))+ratio);"
      "return new QRPolynomial(num,0).mod(e);"
    "}"
  "};"
  "function QRRSBlock(t,d){this.totalCount=t;this.dataCount=d;}"
  "QRRSBlock.RS_BLOCK_TABLE=[[1,26,19],[1,26,16],[1,26,13],[1,26,9],[1,44,34],[1,44,28],[1,44,22],[1,44,16],[1,70,55],[1,70,44],[1,70,34],[2,35,13],[1,100,80],[2,50,32],[2,50,24],[4,25,9]];"
  "QRRSBlock.getRSBlocks=function(typeNumber,errorCorrectionLevel){"
    "var b=QRRSBlock.RS_BLOCK_TABLE[(typeNumber-1)*4+(errorCorrectionLevel==1?0:errorCorrectionLevel==0?1:errorCorrectionLevel==3?2:3)];"
    "var list=[];for(var i=0;i<b[0];i++)list.push(new QRRSBlock(b[1],b[2]));return list;"
  "};"
  "function QRBitBuffer(){this.buffer=[];this.length=0;}"
  "QRBitBuffer.prototype={"
    "put:function(num,len){for(var i=0;i<len;i++)this.putBit(((num>>>(len-i-1))&1)==1);},"
    "getLengthInBits:function(){return this.length;},"
    "putBit:function(bit){"
      "var bufIndex=Math.floor(this.length/8);"
      "if(this.buffer.length<=bufIndex)this.buffer.push(0);"
      "if(bit)this.buffer[bufIndex]|=(0x80>>>(this.length%8));"
      "this.length++;"
    "}"
  "};"
  "return QRCode;"
"})();"

"function generateQR(d){"
  "var text='MAC:'+((d&&d.mac)||'00:08:DC:11:22:33')+'|IP:'+((d&&d.ip)||'192.168.1.200')+'|FW:'+((d&&d.fw)||'v2.0.0');"
  "var canvas=document.getElementById('qr-canvas');"
  "document.getElementById('qr-label').textContent=text;"
  "try{"
    "var qr=new qrcode(0,1);"
    "qr.addData(text);"
    "qr.make();"
    "var count=qr.getModuleCount();"
    "var ctx=canvas.getContext('2d');"
    "var size=canvas.width;"
    "var cellSize=Math.floor(size/(count+4));"
    "var margin=Math.floor((size-cellSize*count)/2);"
    "ctx.fillStyle='#ffffff';"
    "ctx.fillRect(0,0,size,size);"
    "ctx.fillStyle='#050a14';"
    "for(var r=0;r<count;r++)for(var c=0;c<count;c++){"
      "if(qr.isDark(r,c))ctx.fillRect(margin+c*cellSize,margin+r*cellSize,cellSize,cellSize);"
    "}"
  "}catch(e){console.error(e);}"
"}"

/* ----- File Selection ----- */
"function fileSelected(){"
  "var f=document.getElementById('fw-file').files[0];"
  "if(f){"
    "document.getElementById('fw-name').textContent=f.name+' ('+Math.round(f.size/1024)+' KB)';"
    "document.getElementById('btn-flash').disabled=false;"
  "}"
"}"
"function handleDrop(ev){"
  "ev.preventDefault();"
  "var f=ev.dataTransfer.files[0];"
  "if(f){document.getElementById('fw-file')._file=f;"
    "document.getElementById('fw-name').textContent=f.name+' ('+Math.round(f.size/1024)+' KB)';"
    "document.getElementById('btn-flash').disabled=false;"
  "}"
"}"

/* ----- OTA Upload ----- */
"function uploadFirmware(){"
  "var fi=document.getElementById('fw-file');"
  "var file=fi._file||fi.files[0];"
  "if(!file){showMsg('ota-msg','Select a firmware file first.','warn');return;}"
  "var btn=document.getElementById('btn-flash');"
  "btn.disabled=true;"
  "var bar=document.getElementById('ota-bar');"
  "var pct=document.getElementById('ota-pct');"
  "var xhr=new XMLHttpRequest();"
  "xhr.open('POST','/update',true);"
  "xhr.setRequestHeader('Content-Type','application/octet-stream');"
  "xhr.upload.onprogress=function(e){"
    "if(e.lengthComputable){"
      "var p=Math.round(e.loaded/e.total*100);"
      "bar.style.width=p+'%';"
      "pct.textContent='Uploading: '+p+'%';"
    "}"
  "};"
  "xhr.onreadystatechange=function(){"
    "if(xhr.readyState==4){"
      "if(xhr.status==200){"
        "bar.style.width='100%';"
        "pct.textContent='Upload complete!';"
        "showMsg('ota-msg','✅ Firmware received. Device rebooting into bootloader...','ok');"
      "}else{"
        "showMsg('ota-msg','❌ Upload failed: '+xhr.statusText,'err');"
        "btn.disabled=false;"
      "}"
    "}"
  "};"
  "xhr.send(file);"
"}"

/* ----- Alert helper ----- */
"function showMsg(id,txt,type){"
  "var el=document.getElementById(id);"
  "el.className='alert alert-'+type;"
  "el.textContent=txt;"
  "setTimeout(function(){el.textContent='';el.className='';},5000);"
"}"

/* ----- Init ----- */
"buildRelayStatusGrid();"
"buildRelayConfigGrid();"
"startPolling();"

"</script>"
"</body>"
"</html>";

#endif /* WEB_ASSETS_H */
